// This file is auto-generated by @hey-api/openapi-ts

export type PostApiInternalArtifactsData = {
    body?: {
        botId: string;
        title: string;
        sessionKey?: string;
        channelType?: string;
        channelId?: string;
        artifactType?: 'code' | 'content' | 'deployment';
        source?: 'coding' | 'content';
        contentType?: string;
        status?: 'building' | 'live' | 'failed' | 'stopped';
        previewUrl?: string;
        deployTarget?: string;
        linesOfCode?: number;
        fileCount?: number;
        durationMs?: number;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/api/internal/artifacts';
};

export type PostApiInternalArtifactsErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
};

export type PostApiInternalArtifactsError = PostApiInternalArtifactsErrors[keyof PostApiInternalArtifactsErrors];

export type PostApiInternalArtifactsResponses = {
    /**
     * Artifact created
     */
    201: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        artifactType: string;
        source: string;
        contentType: string;
        status: string;
        previewUrl: string;
        deployTarget: string;
        linesOfCode: number;
        fileCount: number;
        durationMs: number;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiInternalArtifactsResponse = PostApiInternalArtifactsResponses[keyof PostApiInternalArtifactsResponses];

export type PatchApiInternalArtifactsByIdData = {
    body?: {
        title?: string;
        status?: 'building' | 'live' | 'failed' | 'stopped';
        previewUrl?: string;
        deployTarget?: string;
        linesOfCode?: number;
        fileCount?: number;
        durationMs?: number;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/internal/artifacts/{id}';
};

export type PatchApiInternalArtifactsByIdErrors = {
    /**
     * Artifact not found
     */
    404: {
        message: string;
    };
};

export type PatchApiInternalArtifactsByIdError = PatchApiInternalArtifactsByIdErrors[keyof PatchApiInternalArtifactsByIdErrors];

export type PatchApiInternalArtifactsByIdResponses = {
    /**
     * Artifact updated
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        artifactType: string;
        source: string;
        contentType: string;
        status: string;
        previewUrl: string;
        deployTarget: string;
        linesOfCode: number;
        fileCount: number;
        durationMs: number;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiInternalArtifactsByIdResponse = PatchApiInternalArtifactsByIdResponses[keyof PatchApiInternalArtifactsByIdResponses];

export type PostApiInternalSessionsData = {
    body?: {
        botId: string;
        sessionKey: string;
        title: string;
        channelType?: string;
        channelId?: string;
        status?: 'active' | 'ended';
        messageCount?: number;
        lastMessageAt?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/api/internal/sessions';
};

export type PostApiInternalSessionsErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
};

export type PostApiInternalSessionsError = PostApiInternalSessionsErrors[keyof PostApiInternalSessionsErrors];

export type PostApiInternalSessionsResponses = {
    /**
     * Session created or updated
     */
    201: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiInternalSessionsResponse = PostApiInternalSessionsResponses[keyof PostApiInternalSessionsResponses];

export type PatchApiInternalSessionsByIdData = {
    body?: {
        title?: string;
        status?: 'active' | 'ended';
        messageCount?: number;
        lastMessageAt?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/internal/sessions/{id}';
};

export type PatchApiInternalSessionsByIdErrors = {
    /**
     * Session not found
     */
    404: {
        message: string;
    };
};

export type PatchApiInternalSessionsByIdError = PatchApiInternalSessionsByIdErrors[keyof PatchApiInternalSessionsByIdErrors];

export type PatchApiInternalSessionsByIdResponses = {
    /**
     * Session updated
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiInternalSessionsByIdResponse = PatchApiInternalSessionsByIdResponses[keyof PatchApiInternalSessionsByIdResponses];

export type GetApiInternalSkillsLatestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/skills/latest';
};

export type GetApiInternalSkillsLatestErrors = {
    /**
     * Unauthorized
     */
    401: {
        message: string;
    };
};

export type GetApiInternalSkillsLatestError = GetApiInternalSkillsLatestErrors[keyof GetApiInternalSkillsLatestErrors];

export type GetApiInternalSkillsLatestResponses = {
    /**
     * Latest skills snapshot
     */
    200: {
        version: number;
        skillsHash: string;
        skills: {
            [key: string]: string;
        };
        createdAt: string;
    };
};

export type GetApiInternalSkillsLatestResponse = GetApiInternalSkillsLatestResponses[keyof GetApiInternalSkillsLatestResponses];

export type PutApiInternalSkillsByNameData = {
    body?: {
        content: string;
        status?: 'active' | 'inactive';
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/internal/skills/{name}';
};

export type PutApiInternalSkillsByNameErrors = {
    /**
     * Invalid name or body
     */
    400: {
        message: string;
    };
    /**
     * Unauthorized
     */
    401: {
        message: string;
    };
};

export type PutApiInternalSkillsByNameError = PutApiInternalSkillsByNameErrors[keyof PutApiInternalSkillsByNameErrors];

export type PutApiInternalSkillsByNameResponses = {
    /**
     * Skill upserted
     */
    200: {
        ok: boolean;
        name: string;
        version: number;
    };
};

export type PutApiInternalSkillsByNameResponse = PutApiInternalSkillsByNameResponses[keyof PutApiInternalSkillsByNameResponses];

export type GetApiV1MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type GetApiV1MeResponses = {
    /**
     * Current user profile
     */
    200: {
        id: string;
        email: string;
        name: string;
        image?: string;
        plan: string;
        inviteAccepted: boolean;
        onboardingCompleted: boolean;
    };
};

export type GetApiV1MeResponse = GetApiV1MeResponses[keyof GetApiV1MeResponses];

export type PostApiV1OnboardingCompleteData = {
    body?: {
        role: string;
        company?: string;
        useCases: Array<string>;
        referralSource: string;
        referralDetail?: string;
        channelVotes?: Array<string>;
        selectedAvatar: string;
        avatarVotes?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/onboarding/complete';
};

export type PostApiV1OnboardingCompleteResponses = {
    /**
     * Onboarding completed
     */
    200: {
        ok: boolean;
    };
};

export type PostApiV1OnboardingCompleteResponse = PostApiV1OnboardingCompleteResponses[keyof PostApiV1OnboardingCompleteResponses];

export type GetApiV1BotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/bots';
};

export type GetApiV1BotsResponses = {
    /**
     * Bot list
     */
    200: {
        bots: Array<{
            id: string;
            name: string;
            slug: string;
            poolId: string;
            status: 'active' | 'paused' | 'deleted';
            modelId: string;
            systemPrompt: string;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetApiV1BotsResponse = GetApiV1BotsResponses[keyof GetApiV1BotsResponses];

export type PostApiV1BotsData = {
    body?: {
        name: string;
        slug: string;
        systemPrompt?: string;
        modelId?: string;
        poolId?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/bots';
};

export type PostApiV1BotsErrors = {
    /**
     * Invalid pool state
     */
    400: {
        message: string;
    };
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
    /**
     * Slug already exists
     */
    409: {
        message: string;
    };
};

export type PostApiV1BotsError = PostApiV1BotsErrors[keyof PostApiV1BotsErrors];

export type PostApiV1BotsResponses = {
    /**
     * Bot created
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1BotsResponse = PostApiV1BotsResponses[keyof PostApiV1BotsResponses];

export type DeleteApiV1BotsByBotIdData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}';
};

export type DeleteApiV1BotsByBotIdErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type DeleteApiV1BotsByBotIdError = DeleteApiV1BotsByBotIdErrors[keyof DeleteApiV1BotsByBotIdErrors];

export type DeleteApiV1BotsByBotIdResponses = {
    /**
     * Bot deleted
     */
    200: {
        success: boolean;
    };
};

export type DeleteApiV1BotsByBotIdResponse = DeleteApiV1BotsByBotIdResponses[keyof DeleteApiV1BotsByBotIdResponses];

export type GetApiV1BotsByBotIdData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}';
};

export type GetApiV1BotsByBotIdErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1BotsByBotIdError = GetApiV1BotsByBotIdErrors[keyof GetApiV1BotsByBotIdErrors];

export type GetApiV1BotsByBotIdResponses = {
    /**
     * Bot details
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiV1BotsByBotIdResponse = GetApiV1BotsByBotIdResponses[keyof GetApiV1BotsByBotIdResponses];

export type PatchApiV1BotsByBotIdData = {
    body?: {
        name?: string;
        systemPrompt?: string;
        modelId?: string;
    };
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}';
};

export type PatchApiV1BotsByBotIdErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type PatchApiV1BotsByBotIdError = PatchApiV1BotsByBotIdErrors[keyof PatchApiV1BotsByBotIdErrors];

export type PatchApiV1BotsByBotIdResponses = {
    /**
     * Bot updated
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiV1BotsByBotIdResponse = PatchApiV1BotsByBotIdResponses[keyof PatchApiV1BotsByBotIdResponses];

export type PostApiV1BotsByBotIdPauseData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}/pause';
};

export type PostApiV1BotsByBotIdPauseErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type PostApiV1BotsByBotIdPauseError = PostApiV1BotsByBotIdPauseErrors[keyof PostApiV1BotsByBotIdPauseErrors];

export type PostApiV1BotsByBotIdPauseResponses = {
    /**
     * Bot paused
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1BotsByBotIdPauseResponse = PostApiV1BotsByBotIdPauseResponses[keyof PostApiV1BotsByBotIdPauseResponses];

export type PostApiV1BotsByBotIdResumeData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}/resume';
};

export type PostApiV1BotsByBotIdResumeErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type PostApiV1BotsByBotIdResumeError = PostApiV1BotsByBotIdResumeErrors[keyof PostApiV1BotsByBotIdResumeErrors];

export type PostApiV1BotsByBotIdResumeResponses = {
    /**
     * Bot resumed
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1BotsByBotIdResumeResponse = PostApiV1BotsByBotIdResumeResponses[keyof PostApiV1BotsByBotIdResumeResponses];

export type GetApiV1ChannelsSlackOauthUrlData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/channels/slack/oauth-url';
};

export type GetApiV1ChannelsSlackOauthUrlErrors = {
    /**
     * Slack OAuth not configured
     */
    500: {
        message: string;
    };
};

export type GetApiV1ChannelsSlackOauthUrlError = GetApiV1ChannelsSlackOauthUrlErrors[keyof GetApiV1ChannelsSlackOauthUrlErrors];

export type GetApiV1ChannelsSlackOauthUrlResponses = {
    /**
     * Slack OAuth authorization URL
     */
    200: {
        url: string;
    };
};

export type GetApiV1ChannelsSlackOauthUrlResponse = GetApiV1ChannelsSlackOauthUrlResponses[keyof GetApiV1ChannelsSlackOauthUrlResponses];

export type PostApiV1ChannelsSlackConnectData = {
    body?: {
        botToken: string;
        signingSecret: string;
        teamId?: string;
        teamName?: string;
        appId?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/channels/slack/connect';
};

export type PostApiV1ChannelsSlackConnectErrors = {
    /**
     * Slack already connected
     */
    409: {
        message: string;
    };
};

export type PostApiV1ChannelsSlackConnectError = PostApiV1ChannelsSlackConnectErrors[keyof PostApiV1ChannelsSlackConnectErrors];

export type PostApiV1ChannelsSlackConnectResponses = {
    /**
     * Slack channel connected
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack' | 'discord';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        appId?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1ChannelsSlackConnectResponse = PostApiV1ChannelsSlackConnectResponses[keyof PostApiV1ChannelsSlackConnectResponses];

export type PostApiV1ChannelsDiscordConnectData = {
    body?: {
        botToken: string;
        appId: string;
        guildId?: string;
        guildName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/channels/discord/connect';
};

export type PostApiV1ChannelsDiscordConnectErrors = {
    /**
     * Discord already connected
     */
    409: {
        message: string;
    };
};

export type PostApiV1ChannelsDiscordConnectError = PostApiV1ChannelsDiscordConnectErrors[keyof PostApiV1ChannelsDiscordConnectErrors];

export type PostApiV1ChannelsDiscordConnectResponses = {
    /**
     * Discord channel connected
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack' | 'discord';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        appId?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1ChannelsDiscordConnectResponse = PostApiV1ChannelsDiscordConnectResponses[keyof PostApiV1ChannelsDiscordConnectResponses];

export type GetApiV1ChannelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/channels';
};

export type GetApiV1ChannelsResponses = {
    /**
     * Channel list
     */
    200: {
        channels: Array<{
            id: string;
            botId: string;
            channelType: 'slack' | 'discord';
            accountId: string;
            status: 'pending' | 'connected' | 'disconnected' | 'error';
            teamName: string;
            appId?: string;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetApiV1ChannelsResponse = GetApiV1ChannelsResponses[keyof GetApiV1ChannelsResponses];

export type DeleteApiV1ChannelsByChannelIdData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: never;
    url: '/api/v1/channels/{channelId}';
};

export type DeleteApiV1ChannelsByChannelIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeleteApiV1ChannelsByChannelIdError = DeleteApiV1ChannelsByChannelIdErrors[keyof DeleteApiV1ChannelsByChannelIdErrors];

export type DeleteApiV1ChannelsByChannelIdResponses = {
    /**
     * Channel disconnected
     */
    200: {
        success: boolean;
    };
};

export type DeleteApiV1ChannelsByChannelIdResponse = DeleteApiV1ChannelsByChannelIdResponses[keyof DeleteApiV1ChannelsByChannelIdResponses];

export type GetApiV1ChannelsByChannelIdStatusData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: never;
    url: '/api/v1/channels/{channelId}/status';
};

export type GetApiV1ChannelsByChannelIdStatusErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1ChannelsByChannelIdStatusError = GetApiV1ChannelsByChannelIdStatusErrors[keyof GetApiV1ChannelsByChannelIdStatusErrors];

export type GetApiV1ChannelsByChannelIdStatusResponses = {
    /**
     * Channel status
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack' | 'discord';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        appId?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiV1ChannelsByChannelIdStatusResponse = GetApiV1ChannelsByChannelIdStatusResponses[keyof GetApiV1ChannelsByChannelIdStatusResponses];

export type PostApiV1InviteValidateData = {
    body?: {
        code: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/invite/validate';
};

export type PostApiV1InviteValidateResponses = {
    /**
     * Validation result
     */
    200: {
        valid: boolean;
        message?: string;
    };
};

export type PostApiV1InviteValidateResponse = PostApiV1InviteValidateResponses[keyof PostApiV1InviteValidateResponses];

export type GetApiV1ModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/models';
};

export type GetApiV1ModelsResponses = {
    /**
     * Available models
     */
    200: {
        models: Array<{
            id: string;
            name: string;
            provider: string;
            isDefault?: boolean;
            description?: string;
        }>;
    };
};

export type GetApiV1ModelsResponse = GetApiV1ModelsResponses[keyof GetApiV1ModelsResponses];

export type GetApiInternalPoolsByPoolIdConfigData = {
    body?: never;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/config';
};

export type GetApiInternalPoolsByPoolIdConfigErrors = {
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigError = GetApiInternalPoolsByPoolIdConfigErrors[keyof GetApiInternalPoolsByPoolIdConfigErrors];

export type GetApiInternalPoolsByPoolIdConfigResponses = {
    /**
     * Generated OpenClaw config
     */
    200: {
        gateway: {
            port?: number;
            mode?: 'local';
            bind?: 'loopback' | 'lan' | 'auto';
            auth: {
                mode: 'none' | 'token';
                token?: string;
            };
            reload?: {
                mode: 'off' | 'hot' | 'hybrid';
            };
            controlUi?: {
                allowedOrigins?: Array<string>;
                dangerouslyAllowHostHeaderOriginFallback?: boolean;
            };
        };
        models?: {
            mode?: 'merge' | 'replace';
            providers: {
                [key: string]: {
                    baseUrl: string;
                    apiKey: string;
                    api: string;
                    models: Array<{
                        id: string;
                        name?: string;
                        reasoning?: boolean;
                        input?: Array<string>;
                        cost?: {
                            input: number;
                            output: number;
                            cacheRead?: number;
                            cacheWrite?: number;
                        };
                        contextWindow?: number;
                        maxTokens?: number;
                        compat?: {
                            supportsStore?: boolean;
                        };
                    }>;
                };
            };
        };
        tools?: {
            exec?: {
                security?: 'deny' | 'allowlist' | 'full';
                ask?: 'off' | 'on-miss' | 'always';
                host?: 'sandbox' | 'gateway' | 'node';
            };
        };
        skills?: {
            load?: {
                watch?: boolean;
                watchDebounceMs?: number;
                extraDirs?: Array<string>;
            };
        };
        agents: {
            defaults?: {
                model?: string | {
                    primary: string;
                };
            };
            list: Array<{
                id: string;
                name?: string;
                default?: boolean;
                workspace?: string;
                model?: string | {
                    primary: string;
                    fallbacks?: Array<string>;
                };
            }>;
        };
        channels: {
            slack?: {
                mode?: 'socket' | 'http';
                signingSecret?: string;
                enabled?: boolean;
                groupPolicy?: 'open' | 'allowlist' | 'disabled';
                requireMention?: boolean;
                dmPolicy?: 'pairing' | 'allowlist' | 'open';
                allowFrom?: Array<string>;
                accounts: {
                    [key: string]: {
                        enabled?: boolean;
                        botToken: string;
                        signingSecret?: string;
                        appToken?: string;
                        mode?: 'socket' | 'http';
                        webhookPath?: string;
                        dmPolicy?: 'pairing' | 'allowlist' | 'open';
                        groupPolicy?: 'open' | 'allowlist' | 'disabled';
                        streaming?: 'off' | 'partial' | 'block' | 'progress';
                    };
                };
            };
            discord?: {
                enabled?: boolean;
                groupPolicy?: 'open' | 'allowlist' | 'disabled';
                dmPolicy?: 'pairing' | 'allowlist' | 'open';
                allowFrom?: Array<string>;
                accounts: {
                    [key: string]: {
                        enabled?: boolean;
                        token: string;
                        groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    };
                };
            };
        };
        bindings: Array<{
            agentId: string;
            match: {
                channel: string;
                accountId?: string;
            };
        }>;
        commands?: {
            native?: 'auto' | 'off';
            nativeSkills?: 'auto' | 'off';
            restart?: boolean;
            ownerDisplay?: 'raw' | 'friendly';
        };
    };
};

export type GetApiInternalPoolsByPoolIdConfigResponse = GetApiInternalPoolsByPoolIdConfigResponses[keyof GetApiInternalPoolsByPoolIdConfigResponses];

export type PostApiInternalPoolsRegisterData = {
    body?: {
        poolId: string;
        podIp?: string;
        status?: 'pending' | 'active' | 'degraded' | 'unhealthy' | 'draining' | 'terminated';
    };
    path?: never;
    query?: never;
    url: '/api/internal/pools/register';
};

export type PostApiInternalPoolsRegisterResponses = {
    /**
     * Pool node registered
     */
    200: {
        ok: boolean;
        poolId: string;
    };
};

export type PostApiInternalPoolsRegisterResponse = PostApiInternalPoolsRegisterResponses[keyof PostApiInternalPoolsRegisterResponses];

export type PostApiInternalPoolsHeartbeatData = {
    body?: {
        poolId: string;
        podIp?: string;
        status?: 'pending' | 'active' | 'degraded' | 'unhealthy' | 'draining' | 'terminated';
        lastSeenVersion?: number;
        timestamp?: string;
    };
    path?: never;
    query?: never;
    url: '/api/internal/pools/heartbeat';
};

export type PostApiInternalPoolsHeartbeatResponses = {
    /**
     * Pool node heartbeat accepted
     */
    200: {
        ok: boolean;
        poolId: string;
        status: 'pending' | 'active' | 'degraded' | 'unhealthy' | 'draining' | 'terminated';
    };
};

export type PostApiInternalPoolsHeartbeatResponse = PostApiInternalPoolsHeartbeatResponses[keyof PostApiInternalPoolsHeartbeatResponses];

export type GetApiInternalPoolsByPoolIdConfigLatestData = {
    body?: never;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/config/latest';
};

export type GetApiInternalPoolsByPoolIdConfigLatestErrors = {
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigLatestError = GetApiInternalPoolsByPoolIdConfigLatestErrors[keyof GetApiInternalPoolsByPoolIdConfigLatestErrors];

export type GetApiInternalPoolsByPoolIdConfigLatestResponses = {
    /**
     * Latest pool config snapshot
     */
    200: {
        poolId: string;
        version: number;
        configHash: string;
        config: {
            gateway: {
                port?: number;
                mode?: 'local';
                bind?: 'loopback' | 'lan' | 'auto';
                auth: {
                    mode: 'none' | 'token';
                    token?: string;
                };
                reload?: {
                    mode: 'off' | 'hot' | 'hybrid';
                };
                controlUi?: {
                    allowedOrigins?: Array<string>;
                    dangerouslyAllowHostHeaderOriginFallback?: boolean;
                };
            };
            models?: {
                mode?: 'merge' | 'replace';
                providers: {
                    [key: string]: {
                        baseUrl: string;
                        apiKey: string;
                        api: string;
                        models: Array<{
                            id: string;
                            name?: string;
                            reasoning?: boolean;
                            input?: Array<string>;
                            cost?: {
                                input: number;
                                output: number;
                                cacheRead?: number;
                                cacheWrite?: number;
                            };
                            contextWindow?: number;
                            maxTokens?: number;
                            compat?: {
                                supportsStore?: boolean;
                            };
                        }>;
                    };
                };
            };
            tools?: {
                exec?: {
                    security?: 'deny' | 'allowlist' | 'full';
                    ask?: 'off' | 'on-miss' | 'always';
                    host?: 'sandbox' | 'gateway' | 'node';
                };
            };
            skills?: {
                load?: {
                    watch?: boolean;
                    watchDebounceMs?: number;
                    extraDirs?: Array<string>;
                };
            };
            agents: {
                defaults?: {
                    model?: string | {
                        primary: string;
                    };
                };
                list: Array<{
                    id: string;
                    name?: string;
                    default?: boolean;
                    workspace?: string;
                    model?: string | {
                        primary: string;
                        fallbacks?: Array<string>;
                    };
                }>;
            };
            channels: {
                slack?: {
                    mode?: 'socket' | 'http';
                    signingSecret?: string;
                    enabled?: boolean;
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    requireMention?: boolean;
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    allowFrom?: Array<string>;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            botToken: string;
                            signingSecret?: string;
                            appToken?: string;
                            mode?: 'socket' | 'http';
                            webhookPath?: string;
                            dmPolicy?: 'pairing' | 'allowlist' | 'open';
                            groupPolicy?: 'open' | 'allowlist' | 'disabled';
                            streaming?: 'off' | 'partial' | 'block' | 'progress';
                        };
                    };
                };
                discord?: {
                    enabled?: boolean;
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    allowFrom?: Array<string>;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            token: string;
                            groupPolicy?: 'open' | 'allowlist' | 'disabled';
                        };
                    };
                };
            };
            bindings: Array<{
                agentId: string;
                match: {
                    channel: string;
                    accountId?: string;
                };
            }>;
            commands?: {
                native?: 'auto' | 'off';
                nativeSkills?: 'auto' | 'off';
                restart?: boolean;
                ownerDisplay?: 'raw' | 'friendly';
            };
        };
        createdAt: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigLatestResponse = GetApiInternalPoolsByPoolIdConfigLatestResponses[keyof GetApiInternalPoolsByPoolIdConfigLatestResponses];

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionData = {
    body?: never;
    path: {
        poolId: string;
        version?: number;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/config/versions/{version}';
};

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionErrors = {
    /**
     * Config version not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionError = GetApiInternalPoolsByPoolIdConfigVersionsByVersionErrors[keyof GetApiInternalPoolsByPoolIdConfigVersionsByVersionErrors];

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponses = {
    /**
     * Pool config snapshot by version
     */
    200: {
        poolId: string;
        version: number;
        configHash: string;
        config: {
            gateway: {
                port?: number;
                mode?: 'local';
                bind?: 'loopback' | 'lan' | 'auto';
                auth: {
                    mode: 'none' | 'token';
                    token?: string;
                };
                reload?: {
                    mode: 'off' | 'hot' | 'hybrid';
                };
                controlUi?: {
                    allowedOrigins?: Array<string>;
                    dangerouslyAllowHostHeaderOriginFallback?: boolean;
                };
            };
            models?: {
                mode?: 'merge' | 'replace';
                providers: {
                    [key: string]: {
                        baseUrl: string;
                        apiKey: string;
                        api: string;
                        models: Array<{
                            id: string;
                            name?: string;
                            reasoning?: boolean;
                            input?: Array<string>;
                            cost?: {
                                input: number;
                                output: number;
                                cacheRead?: number;
                                cacheWrite?: number;
                            };
                            contextWindow?: number;
                            maxTokens?: number;
                            compat?: {
                                supportsStore?: boolean;
                            };
                        }>;
                    };
                };
            };
            tools?: {
                exec?: {
                    security?: 'deny' | 'allowlist' | 'full';
                    ask?: 'off' | 'on-miss' | 'always';
                    host?: 'sandbox' | 'gateway' | 'node';
                };
            };
            skills?: {
                load?: {
                    watch?: boolean;
                    watchDebounceMs?: number;
                    extraDirs?: Array<string>;
                };
            };
            agents: {
                defaults?: {
                    model?: string | {
                        primary: string;
                    };
                };
                list: Array<{
                    id: string;
                    name?: string;
                    default?: boolean;
                    workspace?: string;
                    model?: string | {
                        primary: string;
                        fallbacks?: Array<string>;
                    };
                }>;
            };
            channels: {
                slack?: {
                    mode?: 'socket' | 'http';
                    signingSecret?: string;
                    enabled?: boolean;
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    requireMention?: boolean;
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    allowFrom?: Array<string>;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            botToken: string;
                            signingSecret?: string;
                            appToken?: string;
                            mode?: 'socket' | 'http';
                            webhookPath?: string;
                            dmPolicy?: 'pairing' | 'allowlist' | 'open';
                            groupPolicy?: 'open' | 'allowlist' | 'disabled';
                            streaming?: 'off' | 'partial' | 'block' | 'progress';
                        };
                    };
                };
                discord?: {
                    enabled?: boolean;
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    allowFrom?: Array<string>;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            token: string;
                            groupPolicy?: 'open' | 'allowlist' | 'disabled';
                        };
                    };
                };
            };
            bindings: Array<{
                agentId: string;
                match: {
                    channel: string;
                    accountId?: string;
                };
            }>;
            commands?: {
                native?: 'auto' | 'off';
                nativeSkills?: 'auto' | 'off';
                restart?: boolean;
                ownerDisplay?: 'raw' | 'friendly';
            };
        };
        createdAt: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponse = GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponses[keyof GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponses];

export type GetApiV1ArtifactsData = {
    body?: never;
    path?: never;
    query?: {
        botId?: string;
        sessionKey?: string;
        source?: string;
        status?: string;
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/artifacts';
};

export type GetApiV1ArtifactsResponses = {
    /**
     * Artifact list
     */
    200: {
        artifacts: Array<{
            id: string;
            botId: string;
            sessionKey: string;
            channelType: string;
            channelId: string;
            title: string;
            artifactType: string;
            source: string;
            contentType: string;
            status: string;
            previewUrl: string;
            deployTarget: string;
            linesOfCode: number;
            fileCount: number;
            durationMs: number;
            metadata: {
                [key: string]: unknown;
            };
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        limit: number;
        offset: number;
    };
};

export type GetApiV1ArtifactsResponse = GetApiV1ArtifactsResponses[keyof GetApiV1ArtifactsResponses];

export type GetApiV1ArtifactsStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/artifacts/stats';
};

export type GetApiV1ArtifactsStatsResponses = {
    /**
     * Artifact statistics
     */
    200: {
        totalArtifacts: number;
        liveCount: number;
        buildingCount: number;
        failedCount: number;
        codingCount: number;
        contentCount: number;
        totalLinesOfCode: number;
    };
};

export type GetApiV1ArtifactsStatsResponse = GetApiV1ArtifactsStatsResponses[keyof GetApiV1ArtifactsStatsResponses];

export type DeleteApiV1ArtifactsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/artifacts/{id}';
};

export type DeleteApiV1ArtifactsByIdErrors = {
    /**
     * Artifact not found
     */
    404: {
        message: string;
    };
};

export type DeleteApiV1ArtifactsByIdError = DeleteApiV1ArtifactsByIdErrors[keyof DeleteApiV1ArtifactsByIdErrors];

export type DeleteApiV1ArtifactsByIdResponses = {
    /**
     * Artifact deleted
     */
    200: {
        message: string;
    };
};

export type DeleteApiV1ArtifactsByIdResponse = DeleteApiV1ArtifactsByIdResponses[keyof DeleteApiV1ArtifactsByIdResponses];

export type GetApiV1ArtifactsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/artifacts/{id}';
};

export type GetApiV1ArtifactsByIdErrors = {
    /**
     * Artifact not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1ArtifactsByIdError = GetApiV1ArtifactsByIdErrors[keyof GetApiV1ArtifactsByIdErrors];

export type GetApiV1ArtifactsByIdResponses = {
    /**
     * Artifact details
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        artifactType: string;
        source: string;
        contentType: string;
        status: string;
        previewUrl: string;
        deployTarget: string;
        linesOfCode: number;
        fileCount: number;
        durationMs: number;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiV1ArtifactsByIdResponse = GetApiV1ArtifactsByIdResponses[keyof GetApiV1ArtifactsByIdResponses];

export type GetApiV1SessionsData = {
    body?: never;
    path?: never;
    query?: {
        botId?: string;
        channelType?: string;
        status?: string;
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/sessions';
};

export type GetApiV1SessionsResponses = {
    /**
     * Session list
     */
    200: {
        sessions: Array<{
            id: string;
            botId: string;
            sessionKey: string;
            channelType: string;
            channelId: string;
            title: string;
            status: string;
            messageCount: number;
            lastMessageAt: string;
            metadata: {
                [key: string]: unknown;
            };
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        limit: number;
        offset: number;
    };
};

export type GetApiV1SessionsResponse = GetApiV1SessionsResponses[keyof GetApiV1SessionsResponses];

export type GetApiV1SessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{id}';
};

export type GetApiV1SessionsByIdErrors = {
    /**
     * Session not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1SessionsByIdError = GetApiV1SessionsByIdErrors[keyof GetApiV1SessionsByIdErrors];

export type GetApiV1SessionsByIdResponses = {
    /**
     * Session details
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiV1SessionsByIdResponse = GetApiV1SessionsByIdResponses[keyof GetApiV1SessionsByIdResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};