// This file is auto-generated by @hey-api/openapi-ts

export type PostApiInternalArtifactsData = {
    body?: {
        botId: string;
        title: string;
        sessionKey?: string;
        channelType?: string;
        channelId?: string;
        artifactType?: 'code' | 'content' | 'deployment';
        source?: 'coding' | 'content';
        contentType?: string;
        status?: 'building' | 'live' | 'failed' | 'stopped';
        previewUrl?: string;
        deployTarget?: string;
        linesOfCode?: number;
        fileCount?: number;
        durationMs?: number;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/api/internal/artifacts';
};

export type PostApiInternalArtifactsErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
};

export type PostApiInternalArtifactsError = PostApiInternalArtifactsErrors[keyof PostApiInternalArtifactsErrors];

export type PostApiInternalArtifactsResponses = {
    /**
     * Artifact created
     */
    201: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        artifactType: string;
        source: string;
        contentType: string;
        status: string;
        previewUrl: string;
        deployTarget: string;
        linesOfCode: number;
        fileCount: number;
        durationMs: number;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiInternalArtifactsResponse = PostApiInternalArtifactsResponses[keyof PostApiInternalArtifactsResponses];

export type PatchApiInternalArtifactsByIdData = {
    body?: {
        title?: string;
        status?: 'building' | 'live' | 'failed' | 'stopped';
        previewUrl?: string;
        deployTarget?: string;
        linesOfCode?: number;
        fileCount?: number;
        durationMs?: number;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/internal/artifacts/{id}';
};

export type PatchApiInternalArtifactsByIdErrors = {
    /**
     * Artifact not found
     */
    404: {
        message: string;
    };
};

export type PatchApiInternalArtifactsByIdError = PatchApiInternalArtifactsByIdErrors[keyof PatchApiInternalArtifactsByIdErrors];

export type PatchApiInternalArtifactsByIdResponses = {
    /**
     * Artifact updated
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        artifactType: string;
        source: string;
        contentType: string;
        status: string;
        previewUrl: string;
        deployTarget: string;
        linesOfCode: number;
        fileCount: number;
        durationMs: number;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiInternalArtifactsByIdResponse = PatchApiInternalArtifactsByIdResponses[keyof PatchApiInternalArtifactsByIdResponses];

export type PostApiInternalSessionsData = {
    body?: {
        botId: string;
        sessionKey: string;
        title: string;
        channelType?: string;
        channelId?: string;
        status?: 'active' | 'ended';
        messageCount?: number;
        lastMessageAt?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/api/internal/sessions';
};

export type PostApiInternalSessionsErrors = {
    /**
     * Invalid request
     */
    400: {
        message: string;
    };
};

export type PostApiInternalSessionsError = PostApiInternalSessionsErrors[keyof PostApiInternalSessionsErrors];

export type PostApiInternalSessionsResponses = {
    /**
     * Session created or updated
     */
    201: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiInternalSessionsResponse = PostApiInternalSessionsResponses[keyof PostApiInternalSessionsResponses];

export type PatchApiInternalSessionsByIdData = {
    body?: {
        title?: string;
        status?: 'active' | 'ended';
        messageCount?: number;
        lastMessageAt?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/internal/sessions/{id}';
};

export type PatchApiInternalSessionsByIdErrors = {
    /**
     * Session not found
     */
    404: {
        message: string;
    };
};

export type PatchApiInternalSessionsByIdError = PatchApiInternalSessionsByIdErrors[keyof PatchApiInternalSessionsByIdErrors];

export type PatchApiInternalSessionsByIdResponses = {
    /**
     * Session updated
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiInternalSessionsByIdResponse = PatchApiInternalSessionsByIdResponses[keyof PatchApiInternalSessionsByIdResponses];

export type GetV1BotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/bots';
};

export type GetV1BotsResponses = {
    /**
     * Bot list
     */
    200: {
        bots: Array<{
            id: string;
            name: string;
            slug: string;
            poolId: string;
            status: 'active' | 'paused' | 'deleted';
            modelId: string;
            systemPrompt: string;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetV1BotsResponse = GetV1BotsResponses[keyof GetV1BotsResponses];

export type PostV1BotsData = {
    body?: {
        name: string;
        slug: string;
        systemPrompt?: string;
        modelId?: string;
        poolId?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/bots';
};

export type PostV1BotsErrors = {
    /**
     * Invalid pool state
     */
    400: {
        message: string;
    };
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
    /**
     * Slug already exists
     */
    409: {
        message: string;
    };
};

export type PostV1BotsError = PostV1BotsErrors[keyof PostV1BotsErrors];

export type PostV1BotsResponses = {
    /**
     * Bot created
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostV1BotsResponse = PostV1BotsResponses[keyof PostV1BotsResponses];

export type DeleteV1BotsByBotIdData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}';
};

export type DeleteV1BotsByBotIdErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type DeleteV1BotsByBotIdError = DeleteV1BotsByBotIdErrors[keyof DeleteV1BotsByBotIdErrors];

export type DeleteV1BotsByBotIdResponses = {
    /**
     * Bot deleted
     */
    200: {
        success: boolean;
    };
};

export type DeleteV1BotsByBotIdResponse = DeleteV1BotsByBotIdResponses[keyof DeleteV1BotsByBotIdResponses];

export type GetV1BotsByBotIdData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}';
};

export type GetV1BotsByBotIdErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type GetV1BotsByBotIdError = GetV1BotsByBotIdErrors[keyof GetV1BotsByBotIdErrors];

export type GetV1BotsByBotIdResponses = {
    /**
     * Bot details
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetV1BotsByBotIdResponse = GetV1BotsByBotIdResponses[keyof GetV1BotsByBotIdResponses];

export type PatchV1BotsByBotIdData = {
    body?: {
        name?: string;
        systemPrompt?: string;
        modelId?: string;
    };
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}';
};

export type PatchV1BotsByBotIdErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type PatchV1BotsByBotIdError = PatchV1BotsByBotIdErrors[keyof PatchV1BotsByBotIdErrors];

export type PatchV1BotsByBotIdResponses = {
    /**
     * Bot updated
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchV1BotsByBotIdResponse = PatchV1BotsByBotIdResponses[keyof PatchV1BotsByBotIdResponses];

export type PostV1BotsByBotIdPauseData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}/pause';
};

export type PostV1BotsByBotIdPauseErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type PostV1BotsByBotIdPauseError = PostV1BotsByBotIdPauseErrors[keyof PostV1BotsByBotIdPauseErrors];

export type PostV1BotsByBotIdPauseResponses = {
    /**
     * Bot paused
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostV1BotsByBotIdPauseResponse = PostV1BotsByBotIdPauseResponses[keyof PostV1BotsByBotIdPauseResponses];

export type PostV1BotsByBotIdResumeData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/v1/bots/{botId}/resume';
};

export type PostV1BotsByBotIdResumeErrors = {
    /**
     * Bot not found
     */
    404: {
        message: string;
    };
};

export type PostV1BotsByBotIdResumeError = PostV1BotsByBotIdResumeErrors[keyof PostV1BotsByBotIdResumeErrors];

export type PostV1BotsByBotIdResumeResponses = {
    /**
     * Bot resumed
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostV1BotsByBotIdResumeResponse = PostV1BotsByBotIdResumeResponses[keyof PostV1BotsByBotIdResumeResponses];

export type GetV1ChannelsSlackOauthUrlData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/channels/slack/oauth-url';
};

export type GetV1ChannelsSlackOauthUrlErrors = {
    /**
     * Slack OAuth not configured
     */
    500: {
        message: string;
    };
};

export type GetV1ChannelsSlackOauthUrlError = GetV1ChannelsSlackOauthUrlErrors[keyof GetV1ChannelsSlackOauthUrlErrors];

export type GetV1ChannelsSlackOauthUrlResponses = {
    /**
     * Slack OAuth authorization URL
     */
    200: {
        url: string;
    };
};

export type GetV1ChannelsSlackOauthUrlResponse = GetV1ChannelsSlackOauthUrlResponses[keyof GetV1ChannelsSlackOauthUrlResponses];

export type PostV1ChannelsSlackConnectData = {
    body?: {
        botToken: string;
        signingSecret: string;
        teamId: string;
        teamName?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/channels/slack/connect';
};

export type PostV1ChannelsSlackConnectErrors = {
    /**
     * Slack already connected
     */
    409: {
        message: string;
    };
};

export type PostV1ChannelsSlackConnectError = PostV1ChannelsSlackConnectErrors[keyof PostV1ChannelsSlackConnectErrors];

export type PostV1ChannelsSlackConnectResponses = {
    /**
     * Slack channel connected
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostV1ChannelsSlackConnectResponse = PostV1ChannelsSlackConnectResponses[keyof PostV1ChannelsSlackConnectResponses];

export type GetV1ChannelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/channels';
};

export type GetV1ChannelsResponses = {
    /**
     * Channel list
     */
    200: {
        channels: Array<{
            id: string;
            botId: string;
            channelType: 'slack';
            accountId: string;
            status: 'pending' | 'connected' | 'disconnected' | 'error';
            teamName: string;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetV1ChannelsResponse = GetV1ChannelsResponses[keyof GetV1ChannelsResponses];

export type DeleteV1ChannelsByChannelIdData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: never;
    url: '/v1/channels/{channelId}';
};

export type DeleteV1ChannelsByChannelIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeleteV1ChannelsByChannelIdError = DeleteV1ChannelsByChannelIdErrors[keyof DeleteV1ChannelsByChannelIdErrors];

export type DeleteV1ChannelsByChannelIdResponses = {
    /**
     * Channel disconnected
     */
    200: {
        success: boolean;
    };
};

export type DeleteV1ChannelsByChannelIdResponse = DeleteV1ChannelsByChannelIdResponses[keyof DeleteV1ChannelsByChannelIdResponses];

export type GetV1ChannelsByChannelIdStatusData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: never;
    url: '/v1/channels/{channelId}/status';
};

export type GetV1ChannelsByChannelIdStatusErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetV1ChannelsByChannelIdStatusError = GetV1ChannelsByChannelIdStatusErrors[keyof GetV1ChannelsByChannelIdStatusErrors];

export type GetV1ChannelsByChannelIdStatusResponses = {
    /**
     * Channel status
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetV1ChannelsByChannelIdStatusResponse = GetV1ChannelsByChannelIdStatusResponses[keyof GetV1ChannelsByChannelIdStatusResponses];

export type PostV1InviteValidateData = {
    body?: {
        code: string;
    };
    path?: never;
    query?: never;
    url: '/v1/invite/validate';
};

export type PostV1InviteValidateResponses = {
    /**
     * Validation result
     */
    200: {
        valid: boolean;
        message?: string;
    };
};

export type PostV1InviteValidateResponse = PostV1InviteValidateResponses[keyof PostV1InviteValidateResponses];

export type GetV1ModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/models';
};

export type GetV1ModelsResponses = {
    /**
     * Available models
     */
    200: {
        models: Array<{
            id: string;
            name: string;
            provider: string;
            isDefault?: boolean;
            description?: string;
        }>;
    };
};

export type GetV1ModelsResponse = GetV1ModelsResponses[keyof GetV1ModelsResponses];

export type GetApiInternalPoolsByPoolIdConfigData = {
    body?: never;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/config';
};

export type GetApiInternalPoolsByPoolIdConfigErrors = {
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigError = GetApiInternalPoolsByPoolIdConfigErrors[keyof GetApiInternalPoolsByPoolIdConfigErrors];

export type GetApiInternalPoolsByPoolIdConfigResponses = {
    /**
     * Generated OpenClaw config
     */
    200: {
        gateway: {
            port?: number;
            mode?: 'local';
            bind?: 'loopback' | 'lan' | 'auto';
            auth: {
                mode: 'none' | 'token';
                token?: string;
            };
            reload?: {
                mode: 'off' | 'hot' | 'hybrid';
            };
            controlUi?: {
                allowedOrigins?: Array<string>;
                dangerouslyAllowHostHeaderOriginFallback?: boolean;
            };
        };
        models?: {
            mode?: 'merge' | 'replace';
            providers: {
                [key: string]: {
                    baseUrl: string;
                    apiKey: string;
                    api: string;
                    models: Array<{
                        id: string;
                        name?: string;
                        reasoning?: boolean;
                        input?: Array<string>;
                        cost?: {
                            input: number;
                            output: number;
                            cacheRead?: number;
                            cacheWrite?: number;
                        };
                        contextWindow?: number;
                        maxTokens?: number;
                        compat?: {
                            supportsStore?: boolean;
                        };
                    }>;
                };
            };
        };
        agents: {
            defaults?: {
                model?: string | {
                    primary: string;
                };
            };
            list: Array<{
                id: string;
                name?: string;
                default?: boolean;
                workspace?: string;
                model?: string | {
                    primary: string;
                    fallbacks?: Array<string>;
                };
            }>;
        };
        channels: {
            slack?: {
                mode?: 'socket' | 'http';
                signingSecret?: string;
                enabled?: boolean;
                groupPolicy?: 'open' | 'allowlist' | 'disabled';
                requireMention?: boolean;
                dmPolicy?: 'pairing' | 'allowlist' | 'open';
                allowFrom?: Array<string>;
                accounts: {
                    [key: string]: {
                        enabled?: boolean;
                        botToken: string;
                        signingSecret?: string;
                        appToken?: string;
                        mode?: 'socket' | 'http';
                        webhookPath?: string;
                        dmPolicy?: 'pairing' | 'allowlist' | 'open';
                        groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    };
                };
            };
        };
        bindings: Array<{
            agentId: string;
            match: {
                channel: string;
                accountId?: string;
            };
        }>;
        commands?: {
            native?: 'auto' | 'off';
            nativeSkills?: 'auto' | 'off';
            restart?: boolean;
            ownerDisplay?: 'raw' | 'friendly';
        };
    };
};

export type GetApiInternalPoolsByPoolIdConfigResponse = GetApiInternalPoolsByPoolIdConfigResponses[keyof GetApiInternalPoolsByPoolIdConfigResponses];

export type PostApiInternalPoolsRegisterData = {
    body?: {
        poolId: string;
        podIp?: string;
        status?: 'pending' | 'active' | 'degraded' | 'unhealthy' | 'draining' | 'terminated';
    };
    path?: never;
    query?: never;
    url: '/api/internal/pools/register';
};

export type PostApiInternalPoolsRegisterResponses = {
    /**
     * Pool node registered
     */
    200: {
        ok: boolean;
        poolId: string;
    };
};

export type PostApiInternalPoolsRegisterResponse = PostApiInternalPoolsRegisterResponses[keyof PostApiInternalPoolsRegisterResponses];

export type PostApiInternalPoolsHeartbeatData = {
    body?: {
        poolId: string;
        podIp?: string;
        status?: 'pending' | 'active' | 'degraded' | 'unhealthy' | 'draining' | 'terminated';
        lastSeenVersion?: number;
        timestamp?: string;
    };
    path?: never;
    query?: never;
    url: '/api/internal/pools/heartbeat';
};

export type PostApiInternalPoolsHeartbeatResponses = {
    /**
     * Pool node heartbeat accepted
     */
    200: {
        ok: boolean;
        poolId: string;
        status: 'pending' | 'active' | 'degraded' | 'unhealthy' | 'draining' | 'terminated';
    };
};

export type PostApiInternalPoolsHeartbeatResponse = PostApiInternalPoolsHeartbeatResponses[keyof PostApiInternalPoolsHeartbeatResponses];

export type GetApiInternalPoolsByPoolIdConfigLatestData = {
    body?: never;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/config/latest';
};

export type GetApiInternalPoolsByPoolIdConfigLatestErrors = {
    /**
     * Pool not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigLatestError = GetApiInternalPoolsByPoolIdConfigLatestErrors[keyof GetApiInternalPoolsByPoolIdConfigLatestErrors];

export type GetApiInternalPoolsByPoolIdConfigLatestResponses = {
    /**
     * Latest pool config snapshot
     */
    200: {
        poolId: string;
        version: number;
        configHash: string;
        config: {
            gateway: {
                port?: number;
                mode?: 'local';
                bind?: 'loopback' | 'lan' | 'auto';
                auth: {
                    mode: 'none' | 'token';
                    token?: string;
                };
                reload?: {
                    mode: 'off' | 'hot' | 'hybrid';
                };
                controlUi?: {
                    allowedOrigins?: Array<string>;
                    dangerouslyAllowHostHeaderOriginFallback?: boolean;
                };
            };
            models?: {
                mode?: 'merge' | 'replace';
                providers: {
                    [key: string]: {
                        baseUrl: string;
                        apiKey: string;
                        api: string;
                        models: Array<{
                            id: string;
                            name?: string;
                            reasoning?: boolean;
                            input?: Array<string>;
                            cost?: {
                                input: number;
                                output: number;
                                cacheRead?: number;
                                cacheWrite?: number;
                            };
                            contextWindow?: number;
                            maxTokens?: number;
                            compat?: {
                                supportsStore?: boolean;
                            };
                        }>;
                    };
                };
            };
            agents: {
                defaults?: {
                    model?: string | {
                        primary: string;
                    };
                };
                list: Array<{
                    id: string;
                    name?: string;
                    default?: boolean;
                    workspace?: string;
                    model?: string | {
                        primary: string;
                        fallbacks?: Array<string>;
                    };
                }>;
            };
            channels: {
                slack?: {
                    mode?: 'socket' | 'http';
                    signingSecret?: string;
                    enabled?: boolean;
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    requireMention?: boolean;
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    allowFrom?: Array<string>;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            botToken: string;
                            signingSecret?: string;
                            appToken?: string;
                            mode?: 'socket' | 'http';
                            webhookPath?: string;
                            dmPolicy?: 'pairing' | 'allowlist' | 'open';
                            groupPolicy?: 'open' | 'allowlist' | 'disabled';
                        };
                    };
                };
            };
            bindings: Array<{
                agentId: string;
                match: {
                    channel: string;
                    accountId?: string;
                };
            }>;
            commands?: {
                native?: 'auto' | 'off';
                nativeSkills?: 'auto' | 'off';
                restart?: boolean;
                ownerDisplay?: 'raw' | 'friendly';
            };
        };
        createdAt: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigLatestResponse = GetApiInternalPoolsByPoolIdConfigLatestResponses[keyof GetApiInternalPoolsByPoolIdConfigLatestResponses];

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionData = {
    body?: never;
    path: {
        poolId: string;
        version?: number;
    };
    query?: never;
    url: '/api/internal/pools/{poolId}/config/versions/{version}';
};

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionErrors = {
    /**
     * Config version not found
     */
    404: {
        message: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionError = GetApiInternalPoolsByPoolIdConfigVersionsByVersionErrors[keyof GetApiInternalPoolsByPoolIdConfigVersionsByVersionErrors];

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponses = {
    /**
     * Pool config snapshot by version
     */
    200: {
        poolId: string;
        version: number;
        configHash: string;
        config: {
            gateway: {
                port?: number;
                mode?: 'local';
                bind?: 'loopback' | 'lan' | 'auto';
                auth: {
                    mode: 'none' | 'token';
                    token?: string;
                };
                reload?: {
                    mode: 'off' | 'hot' | 'hybrid';
                };
                controlUi?: {
                    allowedOrigins?: Array<string>;
                    dangerouslyAllowHostHeaderOriginFallback?: boolean;
                };
            };
            models?: {
                mode?: 'merge' | 'replace';
                providers: {
                    [key: string]: {
                        baseUrl: string;
                        apiKey: string;
                        api: string;
                        models: Array<{
                            id: string;
                            name?: string;
                            reasoning?: boolean;
                            input?: Array<string>;
                            cost?: {
                                input: number;
                                output: number;
                                cacheRead?: number;
                                cacheWrite?: number;
                            };
                            contextWindow?: number;
                            maxTokens?: number;
                            compat?: {
                                supportsStore?: boolean;
                            };
                        }>;
                    };
                };
            };
            agents: {
                defaults?: {
                    model?: string | {
                        primary: string;
                    };
                };
                list: Array<{
                    id: string;
                    name?: string;
                    default?: boolean;
                    workspace?: string;
                    model?: string | {
                        primary: string;
                        fallbacks?: Array<string>;
                    };
                }>;
            };
            channels: {
                slack?: {
                    mode?: 'socket' | 'http';
                    signingSecret?: string;
                    enabled?: boolean;
                    groupPolicy?: 'open' | 'allowlist' | 'disabled';
                    requireMention?: boolean;
                    dmPolicy?: 'pairing' | 'allowlist' | 'open';
                    allowFrom?: Array<string>;
                    accounts: {
                        [key: string]: {
                            enabled?: boolean;
                            botToken: string;
                            signingSecret?: string;
                            appToken?: string;
                            mode?: 'socket' | 'http';
                            webhookPath?: string;
                            dmPolicy?: 'pairing' | 'allowlist' | 'open';
                            groupPolicy?: 'open' | 'allowlist' | 'disabled';
                        };
                    };
                };
            };
            bindings: Array<{
                agentId: string;
                match: {
                    channel: string;
                    accountId?: string;
                };
            }>;
            commands?: {
                native?: 'auto' | 'off';
                nativeSkills?: 'auto' | 'off';
                restart?: boolean;
                ownerDisplay?: 'raw' | 'friendly';
            };
        };
        createdAt: string;
    };
};

export type GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponse = GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponses[keyof GetApiInternalPoolsByPoolIdConfigVersionsByVersionResponses];

export type GetV1ArtifactsData = {
    body?: never;
    path?: never;
    query?: {
        botId?: string;
        sessionKey?: string;
        source?: string;
        status?: string;
        limit?: number;
        offset?: number;
    };
    url: '/v1/artifacts';
};

export type GetV1ArtifactsResponses = {
    /**
     * Artifact list
     */
    200: {
        artifacts: Array<{
            id: string;
            botId: string;
            sessionKey: string;
            channelType: string;
            channelId: string;
            title: string;
            artifactType: string;
            source: string;
            contentType: string;
            status: string;
            previewUrl: string;
            deployTarget: string;
            linesOfCode: number;
            fileCount: number;
            durationMs: number;
            metadata: {
                [key: string]: unknown;
            };
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        limit: number;
        offset: number;
    };
};

export type GetV1ArtifactsResponse = GetV1ArtifactsResponses[keyof GetV1ArtifactsResponses];

export type GetV1ArtifactsStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/artifacts/stats';
};

export type GetV1ArtifactsStatsResponses = {
    /**
     * Artifact statistics
     */
    200: {
        totalArtifacts: number;
        liveCount: number;
        buildingCount: number;
        failedCount: number;
        codingCount: number;
        contentCount: number;
        totalLinesOfCode: number;
    };
};

export type GetV1ArtifactsStatsResponse = GetV1ArtifactsStatsResponses[keyof GetV1ArtifactsStatsResponses];

export type DeleteV1ArtifactsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/artifacts/{id}';
};

export type DeleteV1ArtifactsByIdErrors = {
    /**
     * Artifact not found
     */
    404: {
        message: string;
    };
};

export type DeleteV1ArtifactsByIdError = DeleteV1ArtifactsByIdErrors[keyof DeleteV1ArtifactsByIdErrors];

export type DeleteV1ArtifactsByIdResponses = {
    /**
     * Artifact deleted
     */
    200: {
        message: string;
    };
};

export type DeleteV1ArtifactsByIdResponse = DeleteV1ArtifactsByIdResponses[keyof DeleteV1ArtifactsByIdResponses];

export type GetV1ArtifactsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/artifacts/{id}';
};

export type GetV1ArtifactsByIdErrors = {
    /**
     * Artifact not found
     */
    404: {
        message: string;
    };
};

export type GetV1ArtifactsByIdError = GetV1ArtifactsByIdErrors[keyof GetV1ArtifactsByIdErrors];

export type GetV1ArtifactsByIdResponses = {
    /**
     * Artifact details
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        artifactType: string;
        source: string;
        contentType: string;
        status: string;
        previewUrl: string;
        deployTarget: string;
        linesOfCode: number;
        fileCount: number;
        durationMs: number;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type GetV1ArtifactsByIdResponse = GetV1ArtifactsByIdResponses[keyof GetV1ArtifactsByIdResponses];

export type GetV1SessionsData = {
    body?: never;
    path?: never;
    query?: {
        botId?: string;
        channelType?: string;
        status?: string;
        limit?: number;
        offset?: number;
    };
    url: '/v1/sessions';
};

export type GetV1SessionsResponses = {
    /**
     * Session list
     */
    200: {
        sessions: Array<{
            id: string;
            botId: string;
            sessionKey: string;
            channelType: string;
            channelId: string;
            title: string;
            status: string;
            messageCount: number;
            lastMessageAt: string;
            metadata: {
                [key: string]: unknown;
            };
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        limit: number;
        offset: number;
    };
};

export type GetV1SessionsResponse = GetV1SessionsResponses[keyof GetV1SessionsResponses];

export type GetV1SessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/sessions/{id}';
};

export type GetV1SessionsByIdErrors = {
    /**
     * Session not found
     */
    404: {
        message: string;
    };
};

export type GetV1SessionsByIdError = GetV1SessionsByIdErrors[keyof GetV1SessionsByIdErrors];

export type GetV1SessionsByIdResponses = {
    /**
     * Session details
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type GetV1SessionsByIdResponse = GetV1SessionsByIdResponses[keyof GetV1SessionsByIdResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};