// This file is auto-generated by @hey-api/openapi-ts

export type GetApiV1BotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/bots';
};

export type GetApiV1BotsResponses = {
    /**
     * Bot list
     */
    200: {
        bots: Array<{
            id: string;
            name: string;
            slug: string;
            poolId: string;
            status: 'active' | 'paused' | 'deleted';
            modelId: string;
            systemPrompt: string;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetApiV1BotsResponse = GetApiV1BotsResponses[keyof GetApiV1BotsResponses];

export type PostApiV1BotsData = {
    body?: {
        name: string;
        slug: string;
        systemPrompt?: string;
        modelId?: string;
        poolId?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/bots';
};

export type PostApiV1BotsResponses = {
    /**
     * Created
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1BotsResponse = PostApiV1BotsResponses[keyof PostApiV1BotsResponses];

export type DeleteApiV1BotsByBotIdData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}';
};

export type DeleteApiV1BotsByBotIdResponses = {
    /**
     * Deleted
     */
    200: {
        success: boolean;
    };
};

export type DeleteApiV1BotsByBotIdResponse = DeleteApiV1BotsByBotIdResponses[keyof DeleteApiV1BotsByBotIdResponses];

export type GetApiV1BotsByBotIdData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}';
};

export type GetApiV1BotsByBotIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1BotsByBotIdError = GetApiV1BotsByBotIdErrors[keyof GetApiV1BotsByBotIdErrors];

export type GetApiV1BotsByBotIdResponses = {
    /**
     * Bot
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiV1BotsByBotIdResponse = GetApiV1BotsByBotIdResponses[keyof GetApiV1BotsByBotIdResponses];

export type PatchApiV1BotsByBotIdData = {
    body?: {
        name?: string;
        systemPrompt?: string;
        modelId?: string;
    };
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}';
};

export type PatchApiV1BotsByBotIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PatchApiV1BotsByBotIdError = PatchApiV1BotsByBotIdErrors[keyof PatchApiV1BotsByBotIdErrors];

export type PatchApiV1BotsByBotIdResponses = {
    /**
     * Updated
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiV1BotsByBotIdResponse = PatchApiV1BotsByBotIdResponses[keyof PatchApiV1BotsByBotIdResponses];

export type PostApiV1BotsByBotIdPauseData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}/pause';
};

export type PostApiV1BotsByBotIdPauseErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PostApiV1BotsByBotIdPauseError = PostApiV1BotsByBotIdPauseErrors[keyof PostApiV1BotsByBotIdPauseErrors];

export type PostApiV1BotsByBotIdPauseResponses = {
    /**
     * Paused
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1BotsByBotIdPauseResponse = PostApiV1BotsByBotIdPauseResponses[keyof PostApiV1BotsByBotIdPauseResponses];

export type PostApiV1BotsByBotIdResumeData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/v1/bots/{botId}/resume';
};

export type PostApiV1BotsByBotIdResumeErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PostApiV1BotsByBotIdResumeError = PostApiV1BotsByBotIdResumeErrors[keyof PostApiV1BotsByBotIdResumeErrors];

export type PostApiV1BotsByBotIdResumeResponses = {
    /**
     * Resumed
     */
    200: {
        id: string;
        name: string;
        slug: string;
        poolId: string;
        status: 'active' | 'paused' | 'deleted';
        modelId: string;
        systemPrompt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1BotsByBotIdResumeResponse = PostApiV1BotsByBotIdResumeResponses[keyof PostApiV1BotsByBotIdResumeResponses];

export type PostApiV1AuthDesktopAuthorizeData = {
    body?: {
        deviceId: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/desktop-authorize';
};

export type PostApiV1AuthDesktopAuthorizeResponses = {
    /**
     * Desktop authorize
     */
    200: {
        ok: boolean;
        error?: string;
    };
};

export type PostApiV1AuthDesktopAuthorizeResponse = PostApiV1AuthDesktopAuthorizeResponses[keyof PostApiV1AuthDesktopAuthorizeResponses];

export type PostApiV1InviteValidateData = {
    body?: {
        code: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/invite/validate';
};

export type PostApiV1InviteValidateResponses = {
    /**
     * Invite validate
     */
    200: {
        valid: boolean;
        message?: string;
    };
};

export type PostApiV1InviteValidateResponse = PostApiV1InviteValidateResponses[keyof PostApiV1InviteValidateResponses];

export type GetApiV1FeishuBindOauthUrlData = {
    body?: never;
    path?: never;
    query: {
        workspaceKey: string;
        botId: string;
    };
    url: '/api/v1/feishu/bind/oauth-url';
};

export type GetApiV1FeishuBindOauthUrlResponses = {
    /**
     * Feishu bind url
     */
    200: {
        url: string;
    };
};

export type GetApiV1FeishuBindOauthUrlResponse = GetApiV1FeishuBindOauthUrlResponses[keyof GetApiV1FeishuBindOauthUrlResponses];

export type GetApiSharedSlackResolveClaimKeyData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/api/shared-slack/resolve-claim-key';
};

export type GetApiSharedSlackResolveClaimKeyResponses = {
    /**
     * Resolve claim
     */
    200: {
        valid: boolean;
        expired: boolean;
        used: boolean;
        teamId?: string;
        teamName?: string;
        imUserId?: string;
        isExistingWorkspace?: boolean;
        memberCount?: number;
    };
};

export type GetApiSharedSlackResolveClaimKeyResponse = GetApiSharedSlackResolveClaimKeyResponses[keyof GetApiSharedSlackResolveClaimKeyResponses];

export type PostApiV1SharedSlackClaimData = {
    body?: {
        token: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/shared-slack/claim';
};

export type PostApiV1SharedSlackClaimResponses = {
    /**
     * Shared slack claim
     */
    200: {
        ok: boolean;
        orgAuthorized: boolean;
    };
};

export type PostApiV1SharedSlackClaimResponse = PostApiV1SharedSlackClaimResponses[keyof PostApiV1SharedSlackClaimResponses];

export type PostApiInternalDesktopShellOpenData = {
    body?: {
        path: string;
    };
    path?: never;
    query?: never;
    url: '/api/internal/desktop/shell-open';
};

export type PostApiInternalDesktopShellOpenErrors = {
    /**
     * Path not allowed
     */
    403: {
        ok: boolean;
        error?: string;
    };
};

export type PostApiInternalDesktopShellOpenError = PostApiInternalDesktopShellOpenErrors[keyof PostApiInternalDesktopShellOpenErrors];

export type PostApiInternalDesktopShellOpenResponses = {
    /**
     * Shell open result
     */
    200: {
        ok: boolean;
        error?: string;
    };
};

export type PostApiInternalDesktopShellOpenResponse = PostApiInternalDesktopShellOpenResponses[keyof PostApiInternalDesktopShellOpenResponses];

export type GetApiInternalDesktopReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/desktop/ready';
};

export type GetApiInternalDesktopReadyResponses = {
    /**
     * Desktop runtime ready status
     */
    200: {
        ready: boolean;
        workspacePath: string;
        runtime: {
            ok: boolean;
            status: number;
        };
        status: 'active' | 'starting' | 'degraded' | 'unhealthy';
    };
};

export type GetApiInternalDesktopReadyResponse = GetApiInternalDesktopReadyResponses[keyof GetApiInternalDesktopReadyResponses];

export type GetApiInternalDesktopFallbackEventsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/internal/desktop/fallback-events';
};

export type GetApiInternalDesktopFallbackEventsResponses = {
    /**
     * Recent channel fallback diagnostics
     */
    200: {
        events: Array<{
            id: string;
            receivedAt: string;
            channel: string;
            status: string;
            reasonCode: string;
            accountId: string;
            to: string;
            threadId: string;
            sessionKey: string;
            actionId: string;
            fallbackOutcome: 'sent' | 'skipped' | 'failed';
            fallbackReason: string;
            error: string;
            sendResult: {
                runId?: string;
                messageId?: string;
                channel?: string;
                chatId?: string;
                conversationId?: string;
            };
        }>;
    };
};

export type GetApiInternalDesktopFallbackEventsResponse = GetApiInternalDesktopFallbackEventsResponses[keyof GetApiInternalDesktopFallbackEventsResponses];

export type GetApiInternalDesktopPreferencesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/desktop/preferences';
};

export type GetApiInternalDesktopPreferencesResponses = {
    /**
     * Desktop preferences
     */
    200: {
        locale: 'en' | 'zh-CN';
    };
};

export type GetApiInternalDesktopPreferencesResponse = GetApiInternalDesktopPreferencesResponses[keyof GetApiInternalDesktopPreferencesResponses];

export type PatchApiInternalDesktopPreferencesData = {
    body: {
        locale: 'en' | 'zh-CN';
    };
    path?: never;
    query?: never;
    url: '/api/internal/desktop/preferences';
};

export type PatchApiInternalDesktopPreferencesResponses = {
    /**
     * Updated desktop preferences
     */
    200: {
        locale: 'en' | 'zh-CN';
    };
};

export type PatchApiInternalDesktopPreferencesResponse = PatchApiInternalDesktopPreferencesResponses[keyof PatchApiInternalDesktopPreferencesResponses];

export type GetApiInternalDesktopCloudStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/desktop/cloud-status';
};

export type GetApiInternalDesktopCloudStatusResponses = {
    /**
     * Cloud status
     */
    200: {
        connected: boolean;
        polling?: boolean;
        userName?: string;
        userEmail?: string;
        connectedAt?: string;
        models?: Array<{
            id: string;
            name: string;
            provider?: string;
        }>;
        cloudUrl: string;
        linkUrl: string;
        activeProfileName: string;
        profiles: Array<{
            name: string;
            cloudUrl: string;
            linkUrl: string;
            connected: boolean;
            polling?: boolean;
            userName?: string;
            userEmail?: string;
            connectedAt?: string;
            modelCount: number;
        }>;
    };
};

export type GetApiInternalDesktopCloudStatusResponse = GetApiInternalDesktopCloudStatusResponses[keyof GetApiInternalDesktopCloudStatusResponses];

export type PostApiInternalDesktopCloudConnectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/desktop/cloud-connect';
};

export type PostApiInternalDesktopCloudConnectResponses = {
    /**
     * Cloud connect
     */
    200: {
        browserUrl?: string;
        error?: string;
    };
};

export type PostApiInternalDesktopCloudConnectResponse = PostApiInternalDesktopCloudConnectResponses[keyof PostApiInternalDesktopCloudConnectResponses];

export type PostApiInternalDesktopCloudProfileConnectData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/internal/desktop/cloud-profile/connect';
};

export type PostApiInternalDesktopCloudProfileConnectResponses = {
    /**
     * Connect cloud profile
     */
    200: {
        browserUrl?: string;
        error?: string;
        status: {
            connected: boolean;
            polling?: boolean;
            userName?: string;
            userEmail?: string;
            connectedAt?: string;
            models?: Array<{
                id: string;
                name: string;
                provider?: string;
            }>;
            cloudUrl: string;
            linkUrl: string;
            activeProfileName: string;
            profiles: Array<{
                name: string;
                cloudUrl: string;
                linkUrl: string;
                connected: boolean;
                polling?: boolean;
                userName?: string;
                userEmail?: string;
                connectedAt?: string;
                modelCount: number;
            }>;
        };
        configPushed: boolean;
    };
};

export type PostApiInternalDesktopCloudProfileConnectResponse = PostApiInternalDesktopCloudProfileConnectResponses[keyof PostApiInternalDesktopCloudProfileConnectResponses];

export type PostApiInternalDesktopCloudRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/desktop/cloud-refresh';
};

export type PostApiInternalDesktopCloudRefreshResponses = {
    /**
     * Cloud refresh
     */
    200: {
        connected: boolean;
        polling?: boolean;
        userName?: string;
        userEmail?: string;
        connectedAt?: string;
        models?: Array<{
            id: string;
            name: string;
            provider?: string;
        }>;
        cloudUrl: string;
        linkUrl: string;
        activeProfileName: string;
        profiles: Array<{
            name: string;
            cloudUrl: string;
            linkUrl: string;
            connected: boolean;
            polling?: boolean;
            userName?: string;
            userEmail?: string;
            connectedAt?: string;
            modelCount: number;
        }>;
        configPushed: boolean;
    };
};

export type PostApiInternalDesktopCloudRefreshResponse = PostApiInternalDesktopCloudRefreshResponses[keyof PostApiInternalDesktopCloudRefreshResponses];

export type PostApiInternalDesktopCloudProfileCreateData = {
    body: {
        profile: {
            name: string;
            cloudUrl: string;
            linkUrl: string;
        };
    };
    path?: never;
    query?: never;
    url: '/api/internal/desktop/cloud-profile/create';
};

export type PostApiInternalDesktopCloudProfileCreateResponses = {
    /**
     * Create cloud profile
     */
    200: {
        connected: boolean;
        polling?: boolean;
        userName?: string;
        userEmail?: string;
        connectedAt?: string;
        models?: Array<{
            id: string;
            name: string;
            provider?: string;
        }>;
        cloudUrl: string;
        linkUrl: string;
        activeProfileName: string;
        profiles: Array<{
            name: string;
            cloudUrl: string;
            linkUrl: string;
            connected: boolean;
            polling?: boolean;
            userName?: string;
            userEmail?: string;
            connectedAt?: string;
            modelCount: number;
        }>;
        ok: boolean;
        configPushed: boolean;
    };
};

export type PostApiInternalDesktopCloudProfileCreateResponse = PostApiInternalDesktopCloudProfileCreateResponses[keyof PostApiInternalDesktopCloudProfileCreateResponses];

export type PostApiInternalDesktopCloudProfileUpdateData = {
    body: {
        previousName: string;
        profile: {
            name: string;
            cloudUrl: string;
            linkUrl: string;
        };
    };
    path?: never;
    query?: never;
    url: '/api/internal/desktop/cloud-profile/update';
};

export type PostApiInternalDesktopCloudProfileUpdateResponses = {
    /**
     * Update cloud profile
     */
    200: {
        connected: boolean;
        polling?: boolean;
        userName?: string;
        userEmail?: string;
        connectedAt?: string;
        models?: Array<{
            id: string;
            name: string;
            provider?: string;
        }>;
        cloudUrl: string;
        linkUrl: string;
        activeProfileName: string;
        profiles: Array<{
            name: string;
            cloudUrl: string;
            linkUrl: string;
            connected: boolean;
            polling?: boolean;
            userName?: string;
            userEmail?: string;
            connectedAt?: string;
            modelCount: number;
        }>;
        ok: boolean;
        configPushed: boolean;
    };
};

export type PostApiInternalDesktopCloudProfileUpdateResponse = PostApiInternalDesktopCloudProfileUpdateResponses[keyof PostApiInternalDesktopCloudProfileUpdateResponses];

export type PostApiInternalDesktopCloudProfileDeleteData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/internal/desktop/cloud-profile/delete';
};

export type PostApiInternalDesktopCloudProfileDeleteResponses = {
    /**
     * Delete cloud profile
     */
    200: {
        connected: boolean;
        polling?: boolean;
        userName?: string;
        userEmail?: string;
        connectedAt?: string;
        models?: Array<{
            id: string;
            name: string;
            provider?: string;
        }>;
        cloudUrl: string;
        linkUrl: string;
        activeProfileName: string;
        profiles: Array<{
            name: string;
            cloudUrl: string;
            linkUrl: string;
            connected: boolean;
            polling?: boolean;
            userName?: string;
            userEmail?: string;
            connectedAt?: string;
            modelCount: number;
        }>;
        ok: boolean;
        configPushed: boolean;
    };
};

export type PostApiInternalDesktopCloudProfileDeleteResponse = PostApiInternalDesktopCloudProfileDeleteResponses[keyof PostApiInternalDesktopCloudProfileDeleteResponses];

export type PostApiInternalDesktopCloudDisconnectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/desktop/cloud-disconnect';
};

export type PostApiInternalDesktopCloudDisconnectResponses = {
    /**
     * Cloud disconnect
     */
    200: {
        ok: boolean;
    };
};

export type PostApiInternalDesktopCloudDisconnectResponse = PostApiInternalDesktopCloudDisconnectResponses[keyof PostApiInternalDesktopCloudDisconnectResponses];

export type PostApiInternalDesktopCloudProfileDisconnectData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/internal/desktop/cloud-profile/disconnect';
};

export type PostApiInternalDesktopCloudProfileDisconnectResponses = {
    /**
     * Disconnect cloud profile
     */
    200: {
        connected: boolean;
        polling?: boolean;
        userName?: string;
        userEmail?: string;
        connectedAt?: string;
        models?: Array<{
            id: string;
            name: string;
            provider?: string;
        }>;
        cloudUrl: string;
        linkUrl: string;
        activeProfileName: string;
        profiles: Array<{
            name: string;
            cloudUrl: string;
            linkUrl: string;
            connected: boolean;
            polling?: boolean;
            userName?: string;
            userEmail?: string;
            connectedAt?: string;
            modelCount: number;
        }>;
        ok: boolean;
        configPushed: boolean;
    };
};

export type PostApiInternalDesktopCloudProfileDisconnectResponse = PostApiInternalDesktopCloudProfileDisconnectResponses[keyof PostApiInternalDesktopCloudProfileDisconnectResponses];

export type PostApiInternalDesktopCloudProfileSelectData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/internal/desktop/cloud-profile/select';
};

export type PostApiInternalDesktopCloudProfileSelectResponses = {
    /**
     * Switch cloud profile
     */
    200: {
        connected: boolean;
        polling?: boolean;
        userName?: string;
        userEmail?: string;
        connectedAt?: string;
        models?: Array<{
            id: string;
            name: string;
            provider?: string;
        }>;
        cloudUrl: string;
        linkUrl: string;
        activeProfileName: string;
        profiles: Array<{
            name: string;
            cloudUrl: string;
            linkUrl: string;
            connected: boolean;
            polling?: boolean;
            userName?: string;
            userEmail?: string;
            connectedAt?: string;
            modelCount: number;
        }>;
        ok: boolean;
        configPushed: boolean;
    };
};

export type PostApiInternalDesktopCloudProfileSelectResponse = PostApiInternalDesktopCloudProfileSelectResponses[keyof PostApiInternalDesktopCloudProfileSelectResponses];

export type PostApiInternalDesktopCloudProfilesImportData = {
    body: {
        profiles: Array<{
            name: string;
            cloudUrl: string;
            linkUrl: string;
        }>;
    };
    path?: never;
    query?: never;
    url: '/api/internal/desktop/cloud-profiles/import';
};

export type PostApiInternalDesktopCloudProfilesImportResponses = {
    /**
     * Import cloud profiles
     */
    200: {
        connected: boolean;
        polling?: boolean;
        userName?: string;
        userEmail?: string;
        connectedAt?: string;
        models?: Array<{
            id: string;
            name: string;
            provider?: string;
        }>;
        cloudUrl: string;
        linkUrl: string;
        activeProfileName: string;
        profiles: Array<{
            name: string;
            cloudUrl: string;
            linkUrl: string;
            connected: boolean;
            polling?: boolean;
            userName?: string;
            userEmail?: string;
            connectedAt?: string;
            modelCount: number;
        }>;
        ok: boolean;
        configPushed: boolean;
    };
};

export type PostApiInternalDesktopCloudProfilesImportResponse = PostApiInternalDesktopCloudProfilesImportResponses[keyof PostApiInternalDesktopCloudProfilesImportResponses];

export type PutApiInternalDesktopCloudModelsData = {
    body?: {
        enabledModelIds: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/api/internal/desktop/cloud-models';
};

export type PutApiInternalDesktopCloudModelsResponses = {
    /**
     * Cloud models
     */
    200: {
        ok: boolean;
        models?: Array<{
            id: string;
            name: string;
            provider?: string;
        }>;
    };
};

export type PutApiInternalDesktopCloudModelsResponse = PutApiInternalDesktopCloudModelsResponses[keyof PutApiInternalDesktopCloudModelsResponses];

export type GetApiInternalDesktopDefaultModelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/desktop/default-model';
};

export type GetApiInternalDesktopDefaultModelResponses = {
    /**
     * Default model
     */
    200: {
        modelId: string;
    };
};

export type GetApiInternalDesktopDefaultModelResponse = GetApiInternalDesktopDefaultModelResponses[keyof GetApiInternalDesktopDefaultModelResponses];

export type PutApiInternalDesktopDefaultModelData = {
    body?: {
        modelId: string;
    };
    path?: never;
    query?: never;
    url: '/api/internal/desktop/default-model';
};

export type PutApiInternalDesktopDefaultModelResponses = {
    /**
     * Set default model
     */
    200: {
        ok: boolean;
        modelId: string;
        configPushed: boolean;
    };
};

export type PutApiInternalDesktopDefaultModelResponse = PutApiInternalDesktopDefaultModelResponses[keyof PutApiInternalDesktopDefaultModelResponses];

export type GetApiV1ChannelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/channels';
};

export type GetApiV1ChannelsResponses = {
    /**
     * Channel list
     */
    200: {
        channels: Array<{
            id: string;
            botId: string;
            channelType: 'slack' | 'discord' | 'feishu' | 'wechat';
            accountId: string;
            status: 'pending' | 'connected' | 'disconnected' | 'error';
            teamName: string;
            appId?: string;
            botUserId?: string;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetApiV1ChannelsResponse = GetApiV1ChannelsResponses[keyof GetApiV1ChannelsResponses];

export type GetApiV1ChannelsSlackRedirectUriData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/channels/slack/redirect-uri';
};

export type GetApiV1ChannelsSlackRedirectUriResponses = {
    /**
     * Deprecated Slack redirect URI
     */
    200: {
        redirectUri: string;
    };
};

export type GetApiV1ChannelsSlackRedirectUriResponse = GetApiV1ChannelsSlackRedirectUriResponses[keyof GetApiV1ChannelsSlackRedirectUriResponses];

export type GetApiV1ChannelsSlackOauthUrlData = {
    body?: never;
    path?: never;
    query?: {
        returnTo?: string;
    };
    url: '/api/v1/channels/slack/oauth-url';
};

export type GetApiV1ChannelsSlackOauthUrlResponses = {
    /**
     * Deprecated Slack OAuth placeholder
     */
    200: {
        url: string;
        redirectUri: string;
    };
};

export type GetApiV1ChannelsSlackOauthUrlResponse = GetApiV1ChannelsSlackOauthUrlResponses[keyof GetApiV1ChannelsSlackOauthUrlResponses];

export type PostApiV1ChannelsSlackConnectData = {
    body?: {
        botToken: string;
        signingSecret: string;
        teamId?: string;
        teamName?: string;
        appId?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/channels/slack/connect';
};

export type PostApiV1ChannelsSlackConnectErrors = {
    /**
     * Invalid credentials
     */
    409: {
        message: string;
    };
};

export type PostApiV1ChannelsSlackConnectError = PostApiV1ChannelsSlackConnectErrors[keyof PostApiV1ChannelsSlackConnectErrors];

export type PostApiV1ChannelsSlackConnectResponses = {
    /**
     * Connected slack channel
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack' | 'discord' | 'feishu' | 'wechat';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        appId?: string;
        botUserId?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1ChannelsSlackConnectResponse = PostApiV1ChannelsSlackConnectResponses[keyof PostApiV1ChannelsSlackConnectResponses];

export type PostApiV1ChannelsDiscordConnectData = {
    body?: {
        botToken: string;
        appId: string;
        guildId?: string;
        guildName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/channels/discord/connect';
};

export type PostApiV1ChannelsDiscordConnectErrors = {
    /**
     * Invalid credentials
     */
    409: {
        message: string;
    };
};

export type PostApiV1ChannelsDiscordConnectError = PostApiV1ChannelsDiscordConnectErrors[keyof PostApiV1ChannelsDiscordConnectErrors];

export type PostApiV1ChannelsDiscordConnectResponses = {
    /**
     * Connected discord channel
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack' | 'discord' | 'feishu' | 'wechat';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        appId?: string;
        botUserId?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1ChannelsDiscordConnectResponse = PostApiV1ChannelsDiscordConnectResponses[keyof PostApiV1ChannelsDiscordConnectResponses];

export type PostApiV1ChannelsFeishuConnectData = {
    body?: {
        appId: string;
        appSecret: string;
        connectionMode?: 'websocket' | 'webhook';
        verificationToken?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/channels/feishu/connect';
};

export type PostApiV1ChannelsFeishuConnectErrors = {
    /**
     * Invalid credentials
     */
    409: {
        message: string;
    };
};

export type PostApiV1ChannelsFeishuConnectError = PostApiV1ChannelsFeishuConnectErrors[keyof PostApiV1ChannelsFeishuConnectErrors];

export type PostApiV1ChannelsFeishuConnectResponses = {
    /**
     * Connected feishu channel
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack' | 'discord' | 'feishu' | 'wechat';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        appId?: string;
        botUserId?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1ChannelsFeishuConnectResponse = PostApiV1ChannelsFeishuConnectResponses[keyof PostApiV1ChannelsFeishuConnectResponses];

export type GetApiV1ChannelsByChannelIdStatusData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: never;
    url: '/api/v1/channels/{channelId}/status';
};

export type GetApiV1ChannelsByChannelIdStatusErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1ChannelsByChannelIdStatusError = GetApiV1ChannelsByChannelIdStatusErrors[keyof GetApiV1ChannelsByChannelIdStatusErrors];

export type GetApiV1ChannelsByChannelIdStatusResponses = {
    /**
     * Channel status
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack' | 'discord' | 'feishu' | 'wechat';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        appId?: string;
        botUserId?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiV1ChannelsByChannelIdStatusResponse = GetApiV1ChannelsByChannelIdStatusResponses[keyof GetApiV1ChannelsByChannelIdStatusResponses];

export type GetApiV1BotQuotaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/bot-quota';
};

export type GetApiV1BotQuotaResponses = {
    /**
     * Bot quota
     */
    200: {
        available: boolean;
        resetsAt: string;
    };
};

export type GetApiV1BotQuotaResponse = GetApiV1BotQuotaResponses[keyof GetApiV1BotQuotaResponses];

export type DeleteApiV1ChannelsByChannelIdData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: never;
    url: '/api/v1/channels/{channelId}';
};

export type DeleteApiV1ChannelsByChannelIdResponses = {
    /**
     * Disconnected channel
     */
    200: {
        success: boolean;
    };
};

export type DeleteApiV1ChannelsByChannelIdResponse = DeleteApiV1ChannelsByChannelIdResponses[keyof DeleteApiV1ChannelsByChannelIdResponses];

export type PostApiV1ChannelsWechatQrStartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/channels/wechat/qr-start';
};

export type PostApiV1ChannelsWechatQrStartErrors = {
    /**
     * Gateway not connected
     */
    502: {
        message: string;
    };
};

export type PostApiV1ChannelsWechatQrStartError = PostApiV1ChannelsWechatQrStartErrors[keyof PostApiV1ChannelsWechatQrStartErrors];

export type PostApiV1ChannelsWechatQrStartResponses = {
    /**
     * QR code data for WeChat login
     */
    200: {
        qrDataUrl?: string;
        message: string;
        sessionKey?: string;
    };
};

export type PostApiV1ChannelsWechatQrStartResponse = PostApiV1ChannelsWechatQrStartResponses[keyof PostApiV1ChannelsWechatQrStartResponses];

export type PostApiV1ChannelsWechatQrWaitData = {
    body?: {
        sessionKey: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/channels/wechat/qr-wait';
};

export type PostApiV1ChannelsWechatQrWaitErrors = {
    /**
     * Gateway not connected or timeout
     */
    502: {
        message: string;
    };
};

export type PostApiV1ChannelsWechatQrWaitError = PostApiV1ChannelsWechatQrWaitErrors[keyof PostApiV1ChannelsWechatQrWaitErrors];

export type PostApiV1ChannelsWechatQrWaitResponses = {
    /**
     * WeChat QR login result
     */
    200: {
        connected: boolean;
        message: string;
        accountId?: string;
    };
};

export type PostApiV1ChannelsWechatQrWaitResponse = PostApiV1ChannelsWechatQrWaitResponses[keyof PostApiV1ChannelsWechatQrWaitResponses];

export type PostApiV1ChannelsWechatConnectData = {
    body?: {
        accountId: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/channels/wechat/connect';
};

export type PostApiV1ChannelsWechatConnectErrors = {
    /**
     * Connection failed
     */
    409: {
        message: string;
    };
};

export type PostApiV1ChannelsWechatConnectError = PostApiV1ChannelsWechatConnectErrors[keyof PostApiV1ChannelsWechatConnectErrors];

export type PostApiV1ChannelsWechatConnectResponses = {
    /**
     * Connected wechat channel
     */
    200: {
        id: string;
        botId: string;
        channelType: 'slack' | 'discord' | 'feishu' | 'wechat';
        accountId: string;
        status: 'pending' | 'connected' | 'disconnected' | 'error';
        teamName: string;
        appId?: string;
        botUserId?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1ChannelsWechatConnectResponse = PostApiV1ChannelsWechatConnectResponses[keyof PostApiV1ChannelsWechatConnectResponses];

export type GetApiV1ChannelsLiveStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/channels/live-status';
};

export type GetApiV1ChannelsLiveStatusResponses = {
    /**
     * Live channel and agent status from OpenClaw gateway
     */
    200: {
        gatewayConnected: boolean;
        channels: Array<{
            channelType: string;
            channelId: string;
            accountId: string;
            status: 'connected' | 'connecting' | 'disconnected' | 'error' | 'restarting';
            ready: boolean;
            connected: boolean;
            running: boolean;
            configured: boolean;
            lastError: string;
        }>;
        agent: {
            modelId: string;
            modelName: string;
            alive: boolean;
        };
    };
};

export type GetApiV1ChannelsLiveStatusResponse = GetApiV1ChannelsLiveStatusResponses[keyof GetApiV1ChannelsLiveStatusResponses];

export type GetApiV1ChannelsByChannelIdReadinessData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: never;
    url: '/api/v1/channels/{channelId}/readiness';
};

export type GetApiV1ChannelsByChannelIdReadinessErrors = {
    /**
     * Channel not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1ChannelsByChannelIdReadinessError = GetApiV1ChannelsByChannelIdReadinessErrors[keyof GetApiV1ChannelsByChannelIdReadinessErrors];

export type GetApiV1ChannelsByChannelIdReadinessResponses = {
    /**
     * Channel readiness status from OpenClaw gateway
     */
    200: {
        ready: boolean;
        connected: boolean;
        running: boolean;
        configured: boolean;
        lastError: string;
        gatewayConnected: boolean;
    };
};

export type GetApiV1ChannelsByChannelIdReadinessResponse = GetApiV1ChannelsByChannelIdReadinessResponses[keyof GetApiV1ChannelsByChannelIdReadinessResponses];

export type PostApiInternalSessionsData = {
    body?: {
        botId: string;
        sessionKey: string;
        title: string;
        channelType?: string;
        channelId?: string;
        status?: 'active' | 'ended';
        messageCount?: number;
        lastMessageAt?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/api/internal/sessions';
};

export type PostApiInternalSessionsResponses = {
    /**
     * Created or updated session
     */
    201: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiInternalSessionsResponse = PostApiInternalSessionsResponses[keyof PostApiInternalSessionsResponses];

export type PatchApiInternalSessionsByIdData = {
    body?: {
        title?: string;
        status?: 'active' | 'ended';
        messageCount?: number;
        lastMessageAt?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/internal/sessions/{id}';
};

export type PatchApiInternalSessionsByIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PatchApiInternalSessionsByIdError = PatchApiInternalSessionsByIdErrors[keyof PatchApiInternalSessionsByIdErrors];

export type PatchApiInternalSessionsByIdResponses = {
    /**
     * Updated session
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiInternalSessionsByIdResponse = PatchApiInternalSessionsByIdResponses[keyof PatchApiInternalSessionsByIdResponses];

export type GetApiV1SessionsData = {
    body?: never;
    path?: never;
    query?: {
        botId?: string;
        channelType?: string;
        status?: string;
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/sessions';
};

export type GetApiV1SessionsResponses = {
    /**
     * Session list
     */
    200: {
        sessions: Array<{
            id: string;
            botId: string;
            sessionKey: string;
            channelType: string;
            channelId: string;
            title: string;
            status: string;
            messageCount: number;
            lastMessageAt: string;
            metadata: {
                [key: string]: unknown;
            };
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        limit: number;
        offset: number;
    };
};

export type GetApiV1SessionsResponse = GetApiV1SessionsResponses[keyof GetApiV1SessionsResponses];

export type DeleteApiV1SessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{id}';
};

export type DeleteApiV1SessionsByIdResponses = {
    /**
     * Delete session
     */
    200: {
        ok: boolean;
    };
};

export type DeleteApiV1SessionsByIdResponse = DeleteApiV1SessionsByIdResponses[keyof DeleteApiV1SessionsByIdResponses];

export type GetApiV1SessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{id}';
};

export type GetApiV1SessionsByIdErrors = {
    /**
     * Session not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1SessionsByIdError = GetApiV1SessionsByIdErrors[keyof GetApiV1SessionsByIdErrors];

export type GetApiV1SessionsByIdResponses = {
    /**
     * Session details
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiV1SessionsByIdResponse = GetApiV1SessionsByIdResponses[keyof GetApiV1SessionsByIdResponses];

export type PostApiV1SessionsByIdResetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{id}/reset';
};

export type PostApiV1SessionsByIdResetErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PostApiV1SessionsByIdResetError = PostApiV1SessionsByIdResetErrors[keyof PostApiV1SessionsByIdResetErrors];

export type PostApiV1SessionsByIdResetResponses = {
    /**
     * Reset session
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        status: string;
        messageCount: number;
        lastMessageAt: string;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiV1SessionsByIdResetResponse = PostApiV1SessionsByIdResetResponses[keyof PostApiV1SessionsByIdResetResponses];

export type GetApiV1SessionsByIdMessagesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        limit?: number;
    };
    url: '/api/v1/sessions/{id}/messages';
};

export type GetApiV1SessionsByIdMessagesErrors = {
    /**
     * Session not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1SessionsByIdMessagesError = GetApiV1SessionsByIdMessagesErrors[keyof GetApiV1SessionsByIdMessagesErrors];

export type GetApiV1SessionsByIdMessagesResponses = {
    /**
     * Chat messages for the session
     */
    200: {
        messages: Array<{
            id: string;
            role: 'user' | 'assistant';
            content?: unknown;
            timestamp: number;
            createdAt: string;
        }>;
        sessionKey: string;
    };
};

export type GetApiV1SessionsByIdMessagesResponse = GetApiV1SessionsByIdMessagesResponses[keyof GetApiV1SessionsByIdMessagesResponses];

export type GetApiV1ModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/models';
};

export type GetApiV1ModelsResponses = {
    /**
     * Model list
     */
    200: {
        models: Array<{
            id: string;
            name: string;
            provider: string;
            isDefault?: boolean;
            description?: string;
        }>;
    };
};

export type GetApiV1ModelsResponse = GetApiV1ModelsResponses[keyof GetApiV1ModelsResponses];

export type GetApiV1ProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/providers';
};

export type GetApiV1ProvidersResponses = {
    /**
     * Provider list
     */
    200: {
        providers: Array<{
            id: string;
            providerId: string;
            displayName: string;
            enabled: boolean;
            baseUrl: string;
            authMode?: 'apiKey' | 'oauth';
            hasApiKey: boolean;
            hasOauthCredential?: boolean;
            oauthRegion?: 'global' | 'cn';
            oauthEmail?: string;
            modelsJson: string;
            createdAt?: string;
            updatedAt?: string;
        }>;
    };
};

export type GetApiV1ProvidersResponse = GetApiV1ProvidersResponses[keyof GetApiV1ProvidersResponses];

export type DeleteApiV1ProvidersByProviderIdData = {
    body?: never;
    path: {
        providerId: 'anthropic' | 'openai' | 'google' | 'siliconflow' | 'ppio' | 'openrouter' | 'minimax' | 'kimi' | 'glm' | 'moonshot' | 'zai';
    };
    query?: never;
    url: '/api/v1/providers/{providerId}';
};

export type DeleteApiV1ProvidersByProviderIdResponses = {
    /**
     * Deleted provider
     */
    200: {
        ok: boolean;
    };
};

export type DeleteApiV1ProvidersByProviderIdResponse = DeleteApiV1ProvidersByProviderIdResponses[keyof DeleteApiV1ProvidersByProviderIdResponses];

export type PutApiV1ProvidersByProviderIdData = {
    body?: {
        apiKey?: string;
        baseUrl?: string;
        enabled?: boolean;
        displayName?: string;
        authMode?: 'apiKey' | 'oauth';
        modelsJson?: string;
    };
    path: {
        providerId: 'anthropic' | 'openai' | 'google' | 'siliconflow' | 'ppio' | 'openrouter' | 'minimax' | 'kimi' | 'glm' | 'moonshot' | 'zai';
    };
    query?: never;
    url: '/api/v1/providers/{providerId}';
};

export type PutApiV1ProvidersByProviderIdResponses = {
    /**
     * Updated provider
     */
    200: {
        provider: {
            id: string;
            providerId: string;
            displayName: string;
            enabled: boolean;
            baseUrl: string;
            authMode?: 'apiKey' | 'oauth';
            hasApiKey: boolean;
            hasOauthCredential?: boolean;
            oauthRegion?: 'global' | 'cn';
            oauthEmail?: string;
            modelsJson: string;
            createdAt?: string;
            updatedAt?: string;
        };
    };
    /**
     * Created provider
     */
    201: {
        provider: {
            id: string;
            providerId: string;
            displayName: string;
            enabled: boolean;
            baseUrl: string;
            authMode?: 'apiKey' | 'oauth';
            hasApiKey: boolean;
            hasOauthCredential?: boolean;
            oauthRegion?: 'global' | 'cn';
            oauthEmail?: string;
            modelsJson: string;
            createdAt?: string;
            updatedAt?: string;
        };
    };
};

export type PutApiV1ProvidersByProviderIdResponse = PutApiV1ProvidersByProviderIdResponses[keyof PutApiV1ProvidersByProviderIdResponses];

export type GetApiV1ProvidersMinimaxOauthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/providers/minimax/oauth/status';
};

export type GetApiV1ProvidersMinimaxOauthStatusResponses = {
    /**
     * MiniMax OAuth status
     */
    200: {
        connected: boolean;
        inProgress: boolean;
        region?: 'global' | 'cn';
        error?: string;
    };
};

export type GetApiV1ProvidersMinimaxOauthStatusResponse = GetApiV1ProvidersMinimaxOauthStatusResponses[keyof GetApiV1ProvidersMinimaxOauthStatusResponses];

export type DeleteApiV1ProvidersMinimaxOauthLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/providers/minimax/oauth/login';
};

export type DeleteApiV1ProvidersMinimaxOauthLoginResponses = {
    /**
     * Cancel MiniMax OAuth login
     */
    200: {
        connected: boolean;
        inProgress: boolean;
        region?: 'global' | 'cn';
        error?: string;
        cancelled: boolean;
    };
};

export type DeleteApiV1ProvidersMinimaxOauthLoginResponse = DeleteApiV1ProvidersMinimaxOauthLoginResponses[keyof DeleteApiV1ProvidersMinimaxOauthLoginResponses];

export type PostApiV1ProvidersMinimaxOauthLoginData = {
    body?: {
        region: 'global' | 'cn';
    };
    path?: never;
    query?: never;
    url: '/api/v1/providers/minimax/oauth/login';
};

export type PostApiV1ProvidersMinimaxOauthLoginResponses = {
    /**
     * Start MiniMax OAuth login
     */
    200: {
        connected: boolean;
        inProgress: boolean;
        region?: 'global' | 'cn';
        error?: string;
        started: boolean;
        browserUrl?: string;
    };
};

export type PostApiV1ProvidersMinimaxOauthLoginResponse = PostApiV1ProvidersMinimaxOauthLoginResponses[keyof PostApiV1ProvidersMinimaxOauthLoginResponses];

export type PostApiV1ProvidersByProviderIdVerifyData = {
    body?: {
        apiKey: string;
        baseUrl?: string;
    };
    path: {
        providerId: 'anthropic' | 'openai' | 'google' | 'siliconflow' | 'ppio' | 'openrouter' | 'minimax' | 'kimi' | 'glm' | 'moonshot' | 'zai';
    };
    query?: never;
    url: '/api/v1/providers/{providerId}/verify';
};

export type PostApiV1ProvidersByProviderIdVerifyResponses = {
    /**
     * Verify provider
     */
    200: {
        valid: boolean;
        models?: Array<string>;
        error?: string;
    };
};

export type PostApiV1ProvidersByProviderIdVerifyResponse = PostApiV1ProvidersByProviderIdVerifyResponses[keyof PostApiV1ProvidersByProviderIdVerifyResponses];

export type PostApiV1ProvidersByProviderIdOauthStartData = {
    body?: never;
    path: {
        providerId: string;
    };
    query?: never;
    url: '/api/v1/providers/{providerId}/oauth/start';
};

export type PostApiV1ProvidersByProviderIdOauthStartResponses = {
    /**
     * OAuth flow started
     */
    200: {
        browserUrl?: string;
        error?: string;
    };
};

export type PostApiV1ProvidersByProviderIdOauthStartResponse = PostApiV1ProvidersByProviderIdOauthStartResponses[keyof PostApiV1ProvidersByProviderIdOauthStartResponses];

export type GetApiV1ProvidersByProviderIdOauthStatusData = {
    body?: never;
    path: {
        providerId: string;
    };
    query?: never;
    url: '/api/v1/providers/{providerId}/oauth/status';
};

export type GetApiV1ProvidersByProviderIdOauthStatusResponses = {
    /**
     * Current OAuth flow status
     */
    200: {
        status: 'idle' | 'pending' | 'completed' | 'failed';
        error?: string;
        models?: Array<string>;
    };
};

export type GetApiV1ProvidersByProviderIdOauthStatusResponse = GetApiV1ProvidersByProviderIdOauthStatusResponses[keyof GetApiV1ProvidersByProviderIdOauthStatusResponses];

export type GetApiV1ProvidersByProviderIdOauthProviderStatusData = {
    body?: never;
    path: {
        providerId: string;
    };
    query?: never;
    url: '/api/v1/providers/{providerId}/oauth/provider-status';
};

export type GetApiV1ProvidersByProviderIdOauthProviderStatusResponses = {
    /**
     * OAuth provider connection status
     */
    200: {
        connected: boolean;
        provider?: string;
        expiresAt?: number;
        remainingMs?: number;
    };
};

export type GetApiV1ProvidersByProviderIdOauthProviderStatusResponse = GetApiV1ProvidersByProviderIdOauthProviderStatusResponses[keyof GetApiV1ProvidersByProviderIdOauthProviderStatusResponses];

export type PostApiV1ProvidersByProviderIdOauthDisconnectData = {
    body?: never;
    path: {
        providerId: string;
    };
    query?: never;
    url: '/api/v1/providers/{providerId}/oauth/disconnect';
};

export type PostApiV1ProvidersByProviderIdOauthDisconnectResponses = {
    /**
     * OAuth provider disconnected
     */
    200: {
        ok: boolean;
    };
};

export type PostApiV1ProvidersByProviderIdOauthDisconnectResponse = PostApiV1ProvidersByProviderIdOauthDisconnectResponses[keyof PostApiV1ProvidersByProviderIdOauthDisconnectResponses];

export type GetApiV1IntegrationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/integrations';
};

export type GetApiV1IntegrationsResponses = {
    /**
     * Integrations
     */
    200: {
        integrations: Array<{
            id?: string;
            toolkit: {
                slug: string;
                displayName: string;
                description: string;
                iconUrl: string;
                fallbackIconUrl: string;
                category: string;
                authScheme: 'oauth2' | 'api_key_global' | 'api_key_user';
                authFields?: Array<{
                    key: string;
                    label: string;
                    type: 'text' | 'secret';
                    placeholder?: string;
                }>;
            };
            status: 'pending' | 'initiated' | 'active' | 'failed' | 'expired' | 'disconnected';
            connectUrl?: string;
            connectedAt?: string;
            credentialHints?: {
                [key: string]: string;
            };
            returnTo?: string;
            source?: 'page' | 'chat';
        }>;
    };
};

export type GetApiV1IntegrationsResponse = GetApiV1IntegrationsResponses[keyof GetApiV1IntegrationsResponses];

export type PostApiV1IntegrationsConnectData = {
    body?: {
        toolkitSlug: string;
        credentials?: {
            [key: string]: string;
        };
        source?: 'page' | 'chat';
        returnTo?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/integrations/connect';
};

export type PostApiV1IntegrationsConnectResponses = {
    /**
     * Connection initiated
     */
    200: {
        integration: {
            id?: string;
            toolkit: {
                slug: string;
                displayName: string;
                description: string;
                iconUrl: string;
                fallbackIconUrl: string;
                category: string;
                authScheme: 'oauth2' | 'api_key_global' | 'api_key_user';
                authFields?: Array<{
                    key: string;
                    label: string;
                    type: 'text' | 'secret';
                    placeholder?: string;
                }>;
            };
            status: 'pending' | 'initiated' | 'active' | 'failed' | 'expired' | 'disconnected';
            connectUrl?: string;
            connectedAt?: string;
            credentialHints?: {
                [key: string]: string;
            };
            returnTo?: string;
            source?: 'page' | 'chat';
        };
        connectUrl?: string;
        state?: string;
    };
};

export type PostApiV1IntegrationsConnectResponse = PostApiV1IntegrationsConnectResponses[keyof PostApiV1IntegrationsConnectResponses];

export type PostApiV1IntegrationsByIntegrationIdRefreshData = {
    body?: {
        state?: string;
    };
    path: {
        integrationId: string;
    };
    query?: never;
    url: '/api/v1/integrations/{integrationId}/refresh';
};

export type PostApiV1IntegrationsByIntegrationIdRefreshErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type PostApiV1IntegrationsByIntegrationIdRefreshError = PostApiV1IntegrationsByIntegrationIdRefreshErrors[keyof PostApiV1IntegrationsByIntegrationIdRefreshErrors];

export type PostApiV1IntegrationsByIntegrationIdRefreshResponses = {
    /**
     * Refreshed integration
     */
    200: {
        id?: string;
        toolkit: {
            slug: string;
            displayName: string;
            description: string;
            iconUrl: string;
            fallbackIconUrl: string;
            category: string;
            authScheme: 'oauth2' | 'api_key_global' | 'api_key_user';
            authFields?: Array<{
                key: string;
                label: string;
                type: 'text' | 'secret';
                placeholder?: string;
            }>;
        };
        status: 'pending' | 'initiated' | 'active' | 'failed' | 'expired' | 'disconnected';
        connectUrl?: string;
        connectedAt?: string;
        credentialHints?: {
            [key: string]: string;
        };
        returnTo?: string;
        source?: 'page' | 'chat';
    };
};

export type PostApiV1IntegrationsByIntegrationIdRefreshResponse = PostApiV1IntegrationsByIntegrationIdRefreshResponses[keyof PostApiV1IntegrationsByIntegrationIdRefreshResponses];

export type DeleteApiV1IntegrationsByIntegrationIdData = {
    body?: never;
    path: {
        integrationId: string;
    };
    query?: never;
    url: '/api/v1/integrations/{integrationId}';
};

export type DeleteApiV1IntegrationsByIntegrationIdErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type DeleteApiV1IntegrationsByIntegrationIdError = DeleteApiV1IntegrationsByIntegrationIdErrors[keyof DeleteApiV1IntegrationsByIntegrationIdErrors];

export type DeleteApiV1IntegrationsByIntegrationIdResponses = {
    /**
     * Disconnected integration
     */
    200: {
        id?: string;
        toolkit: {
            slug: string;
            displayName: string;
            description: string;
            iconUrl: string;
            fallbackIconUrl: string;
            category: string;
            authScheme: 'oauth2' | 'api_key_global' | 'api_key_user';
            authFields?: Array<{
                key: string;
                label: string;
                type: 'text' | 'secret';
                placeholder?: string;
            }>;
        };
        status: 'pending' | 'initiated' | 'active' | 'failed' | 'expired' | 'disconnected';
        connectUrl?: string;
        connectedAt?: string;
        credentialHints?: {
            [key: string]: string;
        };
        returnTo?: string;
        source?: 'page' | 'chat';
    };
};

export type DeleteApiV1IntegrationsByIntegrationIdResponse = DeleteApiV1IntegrationsByIntegrationIdResponses[keyof DeleteApiV1IntegrationsByIntegrationIdResponses];

export type PostApiInternalArtifactsData = {
    body?: {
        botId: string;
        title: string;
        sessionKey?: string;
        chatId?: string;
        threadId?: string;
        channelType?: string;
        channelId?: string;
        artifactType?: 'code' | 'content' | 'deployment';
        source?: 'coding' | 'content';
        contentType?: string;
        status?: 'building' | 'live' | 'failed' | 'stopped';
        previewUrl?: string;
        deployTarget?: string;
        linesOfCode?: number;
        fileCount?: number;
        durationMs?: number;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/api/internal/artifacts';
};

export type PostApiInternalArtifactsResponses = {
    /**
     * Created artifact
     */
    201: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        artifactType: string;
        source: string;
        contentType: string;
        status: string;
        previewUrl: string;
        deployTarget: string;
        linesOfCode: number;
        fileCount: number;
        durationMs: number;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiInternalArtifactsResponse = PostApiInternalArtifactsResponses[keyof PostApiInternalArtifactsResponses];

export type PatchApiInternalArtifactsByIdData = {
    body?: {
        title?: string;
        status?: 'building' | 'live' | 'failed' | 'stopped';
        previewUrl?: string;
        deployTarget?: string;
        linesOfCode?: number;
        fileCount?: number;
        durationMs?: number;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/internal/artifacts/{id}';
};

export type PatchApiInternalArtifactsByIdErrors = {
    /**
     * Artifact not found
     */
    404: {
        message: string;
    };
};

export type PatchApiInternalArtifactsByIdError = PatchApiInternalArtifactsByIdErrors[keyof PatchApiInternalArtifactsByIdErrors];

export type PatchApiInternalArtifactsByIdResponses = {
    /**
     * Updated artifact
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        artifactType: string;
        source: string;
        contentType: string;
        status: string;
        previewUrl: string;
        deployTarget: string;
        linesOfCode: number;
        fileCount: number;
        durationMs: number;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiInternalArtifactsByIdResponse = PatchApiInternalArtifactsByIdResponses[keyof PatchApiInternalArtifactsByIdResponses];

export type GetApiV1ArtifactsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        sessionKey?: string;
    };
    url: '/api/v1/artifacts';
};

export type GetApiV1ArtifactsResponses = {
    /**
     * Artifacts
     */
    200: {
        artifacts: Array<{
            id: string;
            botId: string;
            sessionKey: string;
            channelType: string;
            channelId: string;
            title: string;
            artifactType: string;
            source: string;
            contentType: string;
            status: string;
            previewUrl: string;
            deployTarget: string;
            linesOfCode: number;
            fileCount: number;
            durationMs: number;
            metadata: {
                [key: string]: unknown;
            };
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        limit: number;
        offset: number;
    };
};

export type GetApiV1ArtifactsResponse = GetApiV1ArtifactsResponses[keyof GetApiV1ArtifactsResponses];

export type GetApiV1ArtifactsStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/artifacts/stats';
};

export type GetApiV1ArtifactsStatsResponses = {
    /**
     * Artifact stats
     */
    200: {
        totalArtifacts: number;
        liveCount: number;
        buildingCount: number;
        failedCount: number;
        codingCount: number;
        contentCount: number;
        totalLinesOfCode: number;
    };
};

export type GetApiV1ArtifactsStatsResponse = GetApiV1ArtifactsStatsResponses[keyof GetApiV1ArtifactsStatsResponses];

export type DeleteApiV1ArtifactsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/artifacts/{id}';
};

export type DeleteApiV1ArtifactsByIdResponses = {
    /**
     * Deleted artifact
     */
    200: {
        ok: boolean;
    };
};

export type DeleteApiV1ArtifactsByIdResponse = DeleteApiV1ArtifactsByIdResponses[keyof DeleteApiV1ArtifactsByIdResponses];

export type GetApiV1ArtifactsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/artifacts/{id}';
};

export type GetApiV1ArtifactsByIdErrors = {
    /**
     * Artifact not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1ArtifactsByIdError = GetApiV1ArtifactsByIdErrors[keyof GetApiV1ArtifactsByIdErrors];

export type GetApiV1ArtifactsByIdResponses = {
    /**
     * Artifact
     */
    200: {
        id: string;
        botId: string;
        sessionKey: string;
        channelType: string;
        channelId: string;
        title: string;
        artifactType: string;
        source: string;
        contentType: string;
        status: string;
        previewUrl: string;
        deployTarget: string;
        linesOfCode: number;
        fileCount: number;
        durationMs: number;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiV1ArtifactsByIdResponse = GetApiV1ArtifactsByIdResponses[keyof GetApiV1ArtifactsByIdResponses];

export type GetApiV1SkillhubCatalogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/skillhub/catalog';
};

export type GetApiV1SkillhubCatalogResponses = {
    /**
     * SkillHub catalog
     */
    200: {
        skills: Array<{
            slug: string;
            name: string;
            description: string;
            downloads: number;
            stars: number;
            tags: Array<string>;
            version: string;
            updatedAt: string;
        }>;
        installedSlugs: Array<string>;
        installedSkills: Array<{
            slug: string;
            source: 'managed' | 'custom';
            name: string;
            description: string;
            installedAt: string;
        }>;
        meta: {
            version: string;
            updatedAt: string;
            skillCount: number;
        };
        queue: Array<{
            slug: string;
            source: 'managed' | 'custom';
            status: 'queued' | 'downloading' | 'installing-deps' | 'done' | 'failed';
            position: number;
            error: string;
            errorCode: 'skill_not_found' | 'rate_limit' | 'unknown';
            retries: number;
            enqueuedAt: string;
        }>;
    };
};

export type GetApiV1SkillhubCatalogResponse = GetApiV1SkillhubCatalogResponses[keyof GetApiV1SkillhubCatalogResponses];

export type PostApiV1SkillhubInstallData = {
    body?: {
        slug: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/skillhub/install';
};

export type PostApiV1SkillhubInstallResponses = {
    /**
     * Install
     */
    200: {
        ok: boolean;
        queued?: boolean;
        slug?: string;
        status?: 'queued' | 'downloading' | 'installing-deps' | 'done' | 'failed';
        position?: number;
        error?: string;
    };
};

export type PostApiV1SkillhubInstallResponse = PostApiV1SkillhubInstallResponses[keyof PostApiV1SkillhubInstallResponses];

export type PostApiV1SkillhubUninstallData = {
    body?: {
        slug: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/skillhub/uninstall';
};

export type PostApiV1SkillhubUninstallResponses = {
    /**
     * Uninstall
     */
    200: {
        ok: boolean;
        error?: string;
    };
};

export type PostApiV1SkillhubUninstallResponse = PostApiV1SkillhubUninstallResponses[keyof PostApiV1SkillhubUninstallResponses];

export type PostApiV1SkillhubRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/skillhub/refresh';
};

export type PostApiV1SkillhubRefreshResponses = {
    /**
     * Refresh
     */
    200: {
        ok: boolean;
        skillCount: number;
        error?: string;
    };
};

export type PostApiV1SkillhubRefreshResponse = PostApiV1SkillhubRefreshResponses[keyof PostApiV1SkillhubRefreshResponses];

export type GetApiV1SkillhubSkillsBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/skillhub/skills/{slug}';
};

export type GetApiV1SkillhubSkillsBySlugErrors = {
    /**
     * Not found
     */
    404: {
        message: string;
    };
};

export type GetApiV1SkillhubSkillsBySlugError = GetApiV1SkillhubSkillsBySlugErrors[keyof GetApiV1SkillhubSkillsBySlugErrors];

export type GetApiV1SkillhubSkillsBySlugResponses = {
    /**
     * Skill detail
     */
    200: {
        slug: string;
        name: string;
        description: string;
        downloads: number;
        stars: number;
        tags: Array<string>;
        version: string;
        updatedAt: string;
        installed: boolean;
        skillContent: string;
        files: Array<string>;
    };
};

export type GetApiV1SkillhubSkillsBySlugResponse = GetApiV1SkillhubSkillsBySlugResponses[keyof GetApiV1SkillhubSkillsBySlugResponses];

export type PostApiV1SkillhubImportData = {
    body?: {
        file: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/skillhub/import';
};

export type PostApiV1SkillhubImportErrors = {
    /**
     * Bad request
     */
    400: {
        ok: false;
        error: string;
    };
};

export type PostApiV1SkillhubImportError = PostApiV1SkillhubImportErrors[keyof PostApiV1SkillhubImportErrors];

export type PostApiV1SkillhubImportResponses = {
    /**
     * Import result
     */
    200: {
        ok: boolean;
        slug?: string;
        error?: string;
    };
};

export type PostApiV1SkillhubImportResponse = PostApiV1SkillhubImportResponses[keyof PostApiV1SkillhubImportResponses];

export type GetApiV1MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type GetApiV1MeResponses = {
    /**
     * Current local user
     */
    200: {
        id: string;
        email: string;
        name: string;
        image?: string;
        plan: string;
        inviteAccepted: boolean;
        onboardingCompleted: boolean;
        authSource?: string;
    };
};

export type GetApiV1MeResponse = GetApiV1MeResponses[keyof GetApiV1MeResponses];

export type PatchApiV1MeData = {
    body?: {
        name?: string;
        image?: string | unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type PatchApiV1MeResponses = {
    /**
     * Updated local user
     */
    200: {
        ok: boolean;
        profile: {
            id: string;
            email: string;
            name: string;
            image?: string;
            plan: string;
            inviteAccepted: boolean;
            onboardingCompleted: boolean;
            authSource?: string;
        };
    };
};

export type PatchApiV1MeResponse = PatchApiV1MeResponses[keyof PatchApiV1MeResponses];

export type PostApiV1MeAuthSourceData = {
    body?: {
        source: 'email' | 'google' | 'slack_shared_claim' | 'IM' | 'Landing';
        detail?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me/auth-source';
};

export type PostApiV1MeAuthSourceResponses = {
    /**
     * Updated auth source
     */
    200: {
        ok: boolean;
    };
};

export type PostApiV1MeAuthSourceResponse = PostApiV1MeAuthSourceResponses[keyof PostApiV1MeAuthSourceResponses];

export type GetApiV1RuntimeConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/runtime-config';
};

export type GetApiV1RuntimeConfigResponses = {
    /**
     * Runtime config
     */
    200: {
        runtime: {
            gateway?: {
                port?: number;
                bind?: 'loopback' | 'lan' | 'auto';
                authMode?: 'none' | 'token';
            };
            defaultModelId?: string;
        };
    };
};

export type GetApiV1RuntimeConfigResponse = GetApiV1RuntimeConfigResponses[keyof GetApiV1RuntimeConfigResponses];

export type PutApiV1RuntimeConfigData = {
    body?: {
        gateway?: {
            port?: number;
            bind?: 'loopback' | 'lan' | 'auto';
            authMode?: 'none' | 'token';
        };
        defaultModelId?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/runtime-config';
};

export type PutApiV1RuntimeConfigResponses = {
    /**
     * Updated runtime config
     */
    200: {
        runtime: {
            gateway?: {
                port?: number;
                bind?: 'loopback' | 'lan' | 'auto';
                authMode?: 'none' | 'token';
            };
            defaultModelId?: string;
        };
    };
};

export type PutApiV1RuntimeConfigResponse = PutApiV1RuntimeConfigResponses[keyof PutApiV1RuntimeConfigResponses];

export type GetApiV1WorkspaceTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/workspace-templates';
};

export type GetApiV1WorkspaceTemplatesResponses = {
    /**
     * Workspace templates
     */
    200: {
        templates: Array<{
            id: string;
            name: string;
            content: string;
            writeMode?: 'seed' | 'inject';
            status?: 'active' | 'inactive';
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetApiV1WorkspaceTemplatesResponse = GetApiV1WorkspaceTemplatesResponses[keyof GetApiV1WorkspaceTemplatesResponses];

export type GetApiInternalWorkspaceTemplatesLatestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/workspace-templates/latest';
};

export type GetApiInternalWorkspaceTemplatesLatestResponses = {
    /**
     * Latest template runtime snapshot
     */
    200: {
        version: number;
        templatesHash: string;
        templates: {
            [key: string]: {
                content: string;
                writeMode: 'seed' | 'inject';
            };
        };
        createdAt: string;
    };
};

export type GetApiInternalWorkspaceTemplatesLatestResponse = GetApiInternalWorkspaceTemplatesLatestResponses[keyof GetApiInternalWorkspaceTemplatesLatestResponses];

export type PutApiInternalWorkspaceTemplatesByNameData = {
    body?: {
        content: string;
        writeMode?: 'seed' | 'inject';
        status?: 'active' | 'inactive';
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/internal/workspace-templates/{name}';
};

export type PutApiInternalWorkspaceTemplatesByNameResponses = {
    /**
     * Upserted template
     */
    200: {
        ok: boolean;
        name: string;
        version: number;
    };
};

export type PutApiInternalWorkspaceTemplatesByNameResponse = PutApiInternalWorkspaceTemplatesByNameResponses[keyof PutApiInternalWorkspaceTemplatesByNameResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};